Repository hmrc/amls-frontend, pull requests merged in 2018-09, with the labels that each got.

#794 whitespace change only
  app/models/tcsp/Tcsp.scala
Labels: pending QA, pending review

#799 added id onto rp check your answers
  app/views/responsiblepeople/detailed_answers.scala.html
Labels: build passing

#802 Added required config for new build process
  app/controllers/AmlsController.scala
  project/MicroService.scala
  project/plugins.sbt
Labels: build passing, pending review

#805 Added ID onto progress page continue button
  app/views/include/submit_application.scala.html
  app/views/registrationprogress/registration_progress.scala.html
Labels: build passing, pending QA, pending review

#804 AMLS-3659 | submitting an incomplete Renewal application
  app/controllers/renewal/RenewalProgressController.scala
  app/services/RenewalService.scala
  app/views/renewal/application_submit.scala.html
  app/views/renewal/renewal_progress.scala.html
  test/services/RenewalServiceSpec.scala
  test/views/renewal/renewal_progressSpec.scala
Labels: build passing, pending QA, pending review

#808 AMLS-4380 | Chains redirect on WhoIsRegisteringController
  app/controllers/declaration/WhoIsRegisteringController.scala
Labels: reviewed

#806 Amls 4347
  app/controllers/responsiblepeople/SoleProprietorOfAnotherBusinessController.scala
  test/controllers/responsiblepeople/SoleProprietorOfAnotherBusinessControllerSpec.scala
  test/services/ConfirmationServiceSpec.scala
Labels: build passing, pending review

#807 Amls 4355
  app/typeclasses/confirmation/ResponsiblePeopleRows.scala
  test/controllers/businessmatching/updateservice/add/WhichFitAndProperControllerSpec.scala
  test/services/ConfirmationServiceSpec.scala
Labels: build passing, reviewed
