Repository hmrc/amls-frontend, pull requests merged in 2018-12, with the labels that each got.

#848 Amls 4166
  app/controllers/LandingController.scala
  app/controllers/LoginEventController.scala
  app/controllers/StatusController.scala
  app/utils/ControllerHelper.scala
  app/views/include/main.scala.html
  app/views/include/main2.scala.html
  app/views/login_event.scala.html
  conf/app.routes
  conf/messages
  public/amls.css
  test/controllers/LandingControllerSpec.scala
  test/controllers/LoginEventControllerSpec.scala
  test/controllers/StatusControllerSpec.scala
  test/generators/StatusGenerator.scala
  test/models/responsiblepeople/ResponsiblePeopleValues.scala
  test/models/responsiblepeople/ResponsiblePersonSpec.scala
  test/utils/ControllerHelperSpec.scala
  test/views/login_eventSpec.scala
Labels: build passing, pending QA, reviewed

#854 Amls 3154 Application fee and reference button change
  app/views/confirmation/confirmation_new.scala.html
  test/views/confirmation/SubmitRegistrationConfirmationViewSpec.scala
Labels: build passing, pending review

#855 Amls 3509 Bank account content change
  app/views/bankdetails/bank_account_name.scala.html
  conf/messages
Labels: build passing, pending review

#856 AMLS-3708 | Content change on "Changed their name page"
  conf/messages
Labels: build passing, pending review

#857 AMLS-3937 | Changed landing page content and button text
  conf/messages
Labels: build passing, pending review

#859 AMLS-3886 | Changed Legend on Renewal Turnover page
  app/views/renewal/amls_turnover.scala.html
Labels: build passing

#863 Amls 3678 - Hint texts for text areas
  app/views/businessactivities/involved_in_other_name.scala.html
  app/views/include/main.scala.html
  app/views/include/main2.scala.html
  app/views/renewal/involved_in_other.scala.html
  app/views/responsiblepeople/experience_training.scala.html
  app/views/responsiblepeople/training.scala.html
  conf/messages
  public/amls.css
Labels: build passing, pending review

#873 Amls 4558 achi
  app/controllers/LandingController.scala
  test/controllers/LandingControllerSpec.scala
Labels: pending QA, reviewed

#869 Amls 4540 - back links: pre-application
  app/views/businessmatching/cannot_continue_with_the_application.scala.html
  app/views/businessmatching/company_registration_number.scala.html
  app/views/businessmatching/psr_number.scala.html
  app/views/businessmatching/register_services.scala.html
  app/views/businessmatching/services.scala.html
  app/views/businessmatching/type_of_business.scala.html
  test/views/businessmatching/PsrNumberViewSpec.scala
  test/views/businessmatching/company_registration_numberSpec.scala
  test/views/businessmatching/register_servicesSpec.scala
  test/views/businessmatching/servicesSpec.scala
  test/views/businessmatching/type_of_businessSpec.scala
Labels: build passing, pending review

#874 Add small margin to bottom of back link
  public/amls.css
Labels: pending QA, pending review

#875 Fix bug in which login events page is not shown when logging in with …
  app/controllers/LandingController.scala
  test/controllers/LandingControllerSpec.scala
Labels: reviewed

#879 Amls 4579 - removed redundant code from service flow
  app/controllers/asp/SummaryController.scala
  app/controllers/estateagentbusiness/SummaryController.scala
  app/controllers/hvd/SummaryController.scala
  app/controllers/msb/SummaryController.scala
  app/controllers/tcsp/SummaryController.scala
  app/services/businessmatching/ServiceFlow.scala
  test/controllers/asp/SummaryControllerSpec.scala
  test/controllers/estateagentbusiness/SummaryControllerSpec.scala
  test/controllers/hvd/SummaryControllerSpec.scala
  test/controllers/msb/SummaryControllerSpec.scala
  test/controllers/tcsp/SummaryControllerSpec.scala
  test/services/businessmatching/updateservice/ServiceFlowSpec.scala
  test/utils/ServiceFlowMocks.scala
Labels: build passing, pending QA, pending review

#876 Amls 3259 new
  app/config/ApplicationConfig.scala
  app/controllers/BaseController.scala
  app/controllers/LandingController.scala
  app/controllers/declaration/AddPersonController.scala
  app/controllers/declaration/DeclarationController.scala
  app/controllers/declaration/WhoIsRegisteringController.scala
  conf/application.conf
  test/controllers/LandingControllerSpec.scala
  test/controllers/declaration/AddPersonControllerSpec.scala
  test/controllers/declaration/DeclarationControllerSpec.scala
  test/controllers/declaration/RegisterPartnersControllerSpec.scala
  test/controllers/declaration/RegisterResponsiblePersonControllerSpec.scala
Labels: pending QA, reviewed

#877 Amls 3268 - hasAccepted toggle removal
  app/config/ApplicationConfig.scala
  app/models/aboutthebusiness/AboutTheBusiness.scala
  app/models/asp/Asp.scala
  app/models/moneyservicebusiness/MoneyServiceBusiness.scala
  app/views/aboutthebusiness/summary.scala.html
  app/views/asp/summary.scala.html
  app/views/msb/summary.scala.html
  app/views/tcsp/summary.scala.html
  conf/application.conf
  test/models/aboutthebusiness/AboutTheBusinessSpec.scala
  test/models/asp/AspSpec.scala
  test/models/businessactivities/BusinessActivitiesSpec.scala
  test/models/businessmatching/BusinessMatchingSpec.scala
  test/models/estateagentbusiness/EstateAgentBusinessSpec.scala
  test/models/hvd/HvdSpec.scala
  test/models/tcsp/TcspSpec.scala
Labels: build passing, reviewed

#878 Amls 4275
  app/config/ApplicationConfig.scala
  app/config/Wiring.scala
  app/connectors/cache/Conversions.scala
  app/connectors/cache/DataCacheConnector.scala
  app/connectors/cache/DataCacheConnectorMigrator.scala
  app/connectors/cache/MongoCacheConnector.scala
  app/connectors/cache/Save4LaterCacheConnector.scala
  app/controllers/LandingController.scala
  app/controllers/testonly/TestOnlyController.scala
  app/models/UpdateMongoCacheResponse.scala
  app/modules/Module.scala
  app/services/UpdateMongoCacheService.scala
  conf/application.conf
  conf/testOnlyDoNotUseInAppConf.routes
  test/connectors/cache/DataCacheConnectorMigratorSpec.scala
  test/connectors/cache/DataCacheConnectorSpec.scala
  test/connectors/cache/MongoCacheConnectorSpec.scala
  test/controllers/LandingControllerSpec.scala
  test/controllers/RegistrationProgressControllerSpec.scala
  test/controllers/aboutthebusiness/ConfirmRegisteredOfficeControllerSpec.scala
  test/controllers/aboutthebusiness/LettersAddressControllerSpec.scala
  test/controllers/businessactivities/NCARegisteredControllerSpec.scala
  test/controllers/hvd/CashPaymentControllerSpec.scala
  test/controllers/hvd/ExciseGoodsControllerSpec.scala
  test/controllers/hvd/HowWillYouSellGoodsControllerSpec.scala
  test/controllers/hvd/LinkedCashPaymentsControllerSpec.scala
  test/controllers/msb/CETransactionsInNext12MonthsControllerSpec.scala
  test/controllers/msb/FXTransactionsInNext12MonthsControllerSpec.scala
  test/controllers/renewal/CETransactionsInLast12MonthsControllerSpec.scala
  test/controllers/renewal/FXTransactionsInLast12MonthsControllerSpec.scala
  test/controllers/responsiblepeople/AdditionalAddressControllerSpec.scala
  test/controllers/responsiblepeople/CountryOfBirthControllerSpec.scala
  test/controllers/responsiblepeople/CurrentAddressControllerSpec.scala
  test/controllers/responsiblepeople/NewHomeAddressDateOfChangeControllerSpec.scala
  test/controllers/responsiblepeople/SoleProprietorOfAnotherBusinessControllerSpec.scala
  test/controllers/tcsp/TcspTypesControllerSpec.scala
  test/controllers/tradingpremises/RegisteringAgentPremisesControllerSpec.scala
  test/controllers/tradingpremises/RemoveAgentPremisesReasonsControllerSpec.scala
  test/controllers/tradingpremises/WhereAreTradingPremisesControllerSpec.scala
  test/models/businessmatching/BusinessMatchingSpec.scala
  test/models/estateagentbusiness/EstateAgentBusinessSpec.scala
  test/services/UpdateMongoCacheServiceSpec.scala
Labels: TECH DEBT, reviewed

#880 Amls 4276 achi
  app/connectors/cache/DataCacheConnector.scala
  app/connectors/cache/MongoCacheConnector.scala
  app/models/bankdetails/BankDetails.scala
  app/models/responsiblepeople/ResponsiblePerson.scala
  app/services/LandingService.scala
  app/services/cache/MongoCacheClient.scala
  test/connectors/cache/MongoCacheConnectorSpec.scala
  test/services/LandingServiceSpec.scala
Labels: reviewed

#881 Amls 3260
  app/config/ApplicationConfig.scala
  app/controllers/aboutthebusiness/RegisteredOfficeDateOfChangeController.scala
  app/controllers/tradingpremises/AgentCompanyDetailsController.scala
  app/controllers/tradingpremises/AgentNameController.scala
  app/controllers/tradingpremises/BusinessStructureController.scala
  app/controllers/tradingpremises/MSBServicesController.scala
  app/controllers/tradingpremises/SummaryController.scala
  app/controllers/tradingpremises/WhatDoesYourBusinessDoController.scala
  app/controllers/tradingpremises/WhereAreTradingPremisesController.scala
  app/models/declaration/AddPerson.scala
  app/models/moneyservicebusiness/WhichCurrencies.scala
  app/models/renewal/WhichCurrencies.scala
  app/models/tradingpremises/AgentName.scala
  app/views/msb/summary.scala.html
  app/views/renewal/summary.scala.html
  app/views/renewal/which_currencies.scala.html
  app/views/tradingpremises/agent_name.scala.html
  conf/application.conf
  test/controllers/aboutthebusiness/RegisteredOfficeControllerSpec.scala
  test/controllers/aboutthebusiness/RegisteredOfficeDateOfChangeControllerSpec.scala
  test/controllers/declaration/AddPersonControllerSpec.scala
  test/controllers/hvd/ExciseGoodsControllerSpec.scala
  test/controllers/hvd/HowWillYouSellGoodsControllerSpec.scala
  test/controllers/hvd/ProductsControllerSpec.scala
  test/controllers/responsiblepeople/CurrentAddressControllerSpec.scala
  test/controllers/responsiblepeople/CurrentAddressDateOfChangeControllerSpec.scala
  test/controllers/responsiblepeople/TimeAtCurrentAddressControllerNoRelease7Spec.scala
  test/controllers/responsiblepeople/TimeAtCurrentAddressControllerSpec.scala
  test/controllers/tradingpremises/BusinessStructureControllerRelease7Spec.scala
  test/controllers/tradingpremises/BusinessStructureControllerSpec.scala
  test/models/declaration/AddPersonSpec.scala
  test/models/declaration/RoleWithinBusinessSpec.scala
  test/models/declaration/release7/RoleWithinBusinessRelease7Spec.scala
  test/models/moneyservicebusiness/WhichCurrenciesPreRelease7Spec.scala
  test/models/moneyservicebusiness/WhichCurrenciesSpec.scala
  test/models/renewal/WhichCurrenciesSpec.scala
  test/models/tradingpremises/AgentNameSpec.scala
  test/views/msb/summaryPreRelease7Spec.scala
  test/views/msb/which_currenciesPreRelease7Spec.scala
  test/views/msb/which_currenciesSpec.scala
  test/views/renewal/which_currenciesSpec.scala
  test/views/tradingpremises/agent_nameSpec.scala
  test/views/tradingpremises/summarySpec.scala
Labels: reviewed
