Repository hmrc/amls-frontend, pull requests merged in 2018-11, with the labels that each got.

#831 Amls 4425
  app/typeclasses/confirmation/ConfirmationBreakdownRows.scala
  app/typeclasses/confirmation/FeeCalculations.scala
  app/typeclasses/confirmation/ResponsiblePeopleRows.scala
  conf/messages
  test/services/ConfirmationServiceSpec.scala
Labels: build passing, reviewed

#830 Amls 4455
  app/views/confirmation/breakdown.scala.html
  app/views/confirmation/confirm_amendvariation.scala.html
  app/views/confirmation/confirm_renewal.scala.html
  app/views/confirmation/confirmation.scala.html
  app/views/confirmation/confirmation_new.scala.html
  app/views/fee_guidance.scala.html
  conf/messages
  public/amls.css
  test/views/confirmation/AmendmentConfirmationViewSpec.scala
  test/views/confirmation/RenewalConfirmationViewSpec.scala
Labels: build passing, reviewed

#837 added IDs to status
  app/views/status/status_deregistered.scala.html
  app/views/status/status_expired.scala.html
  app/views/status/status_incomplete.scala.html
  app/views/status/status_not_submitted.scala.html
  app/views/status/status_rejected.scala.html
  app/views/status/status_renewal_incomplete.scala.html
  app/views/status/status_renewal_not_submitted.scala.html
  app/views/status/status_renewal_submitted.scala.html
  app/views/status/status_revoked.scala.html
  app/views/status/status_submitted.scala.html
  app/views/status/status_withdrawn.scala.html
Labels: reviewed

#838 Fix dev and staging issue with fees
  app/connectors/TaxEnrolmentsConnector.scala
  conf/application.conf
  test/connectors/TaxEnrolmentsConnectorSpec.scala
Labels: pending QA

#836 Amls 4023
  app/views/submission/duplicate_submission.scala.html
  conf/messages
  test/views/submission/duplicate_submissionSpec.scala
Labels: build passing, reviewed

#839 AMLS-4489 | Accessibility issue fix.
  app/views/aboutthebusiness/corporation_tax_registered.scala.html
  app/views/aboutthebusiness/previously_registered.scala.html
  app/views/aboutthebusiness/vat_registered.scala.html
  app/views/bankdetails/bank_account_is_uk.scala.html
  app/views/businessmatching/company_registration_number.scala.html
  app/views/businessmatching/psr_number.scala.html
  app/views/businessmatching/updateservice/add/business_applied_for_psr_number.scala.html
Labels: build passing, pending review

#840 AMLS-4459 | Content update on approval check page.
  conf/messages
Labels: build passing, pending review

#841 AMLS-3399 | Content update on what you need page
  app/views/responsiblepeople/what_you_need.scala.html
  conf/messages
  test/views/responsiblepeople/what_you_needSpec.scala
Labels: build passing, pending review

#843 AMLS-3636 | Removed returnLink from preApp postcode page
  app/views/businessmatching/confirm_postcode.scala.html
Labels: build passing, reviewed

#844 AMLS-3395 | Fixed not correctly referenced field names of GA attributes.
  app/views/include/forms2/country.scala.html
  app/views/include/forms2/currency.scala.html
  app/views/include/forms2/inlineRadioGroup.scala.html
  app/views/include/forms2/labelWithInput.scala.html
  app/views/include/forms2/panel.scala.html
  app/views/include/forms2/radioGroup.scala.html
  app/views/include/forms2/rpInput.scala.html
Labels: build passing, pending QA, pending review

#842 Amls 4447
  app/controllers/SubmissionController.scala
  app/views/submission/bad_request.scala.html
  conf/messages
  test/controllers/SubmissionControllerSpec.scala
  test/views/submission/bad_requestSpec.scala
Labels: reviewed

#845 AMLS-4516 | Bug fix
  app/controllers/hvd/ExpectToReceiveCashPaymentsController.scala
  test/controllers/hvd/ExpectToReceiveCashPaymentsControllerSpec.scala
Labels: build passing, pending QA, pending review

#846 Amls 4507 | Change Message content from 'Home page' to 'status page'
  app/services/notifications/v2m0/MessageDetails.scala
  app/views/notifications/v2m0/message_details.scala.html
  app/views/notifications/v2m0/minded_to_reject.scala.html
  app/views/notifications/v2m0/minded_to_revoke.scala.html
  app/views/notifications/v2m0/no_longer_minded_to_reject.scala.html
  app/views/notifications/v2m0/no_longer_minded_to_revoke.scala.html
  app/views/notifications/v2m0/rejection_reasons.scala.html
  app/views/notifications/v2m0/revocation_reasons.scala.html
  conf/notifications/v2m0/services.txt
  conf/notifications/v2m0/views.txt
  documentation/template-versions.md
  test/NotificationsCheckSumSpec.scala
  test/services/notifications/v2m0/MessageDetailsSpec.scala
  test/views/notifications/v2m0/minded_to_rejectSpec.scala
  test/views/notifications/v2m0/minded_to_revokeSpec.scala
  test/views/notifications/v2m0/no_longer_minded_to_rejectSpec.scala
  test/views/notifications/v2m0/no_longer_minded_to_revokeSpec.scala
  test/views/notifications/v2m0/rejection_reasonsSpec.scala
  test/views/notifications/v2m0/revocation_reasonsSpec.scala
Labels: build passing, pending review

#849 For MSB TCSP sectors set approval equal to fit and proper
  app/models/responsiblepeople/ResponsiblePerson.scala
  test/models/responsiblepeople/ResponsiblePersonSpec.scala
Labels: pending QA, pending review
