Repository hmrc/amls-frontend, pull requests merged in 2018-07, with the labels that each got.

#745 Amls 4111
  app/views/businessmatching/updateservice/add/update_services_summary.scala.html
  test/utils/UpdateServicesSummaryFixtures.scala
  test/views/businessmatching/updateservice/add/update_services_summarySpec.scala
Labels: pending QA, pending review

#749 Amls 4125
  app/views/msb/which_currencies.scala.html
  public/amls.js
Labels: pending review

#750 Add element id to error-notification elements for GA
  app/views/include/forms2/country.scala.html
  app/views/include/forms2/currency.scala.html
  app/views/include/forms2/inlineRadioGroup.scala.html
  app/views/include/forms2/labelWithInput.scala.html
  app/views/include/forms2/panel.scala.html
  app/views/include/forms2/radioGroup.scala.html
  app/views/include/forms2/rpInput.scala.html
Labels: automation passing, build passing, pending QA, pending review

#753 AMLS-4079 Altered cache migration strategy
  app/services/businessmatching/ServiceFlow.scala
  app/views/include/main.scala.html
  app/views/include/main2.scala.html
  test/services/businessmatching/updateservice/ServiceFlowSpec.scala
Labels: pending review

#755 AMLS-4087 - Implement tax-enrolments service
  app/config/ApplicationConfig.scala
  app/connectors/TaxEnrolmentsConnector.scala
  app/services/AuthEnrolmentsService.scala
  conf/application.conf
  test/connectors/TaxEnrolmentsConnectorSpec.scala
  test/services/AuthEnrolmentsServiceSpec.scala
Labels: automation passing, build passing, pending QA, pending review

#757 Amls 4090 - Remove Refresh Profile and AuthenicatorConnector
  app/connectors/AuthenticatorConnector.scala
  app/controllers/ConfirmationController.scala
  app/controllers/StatusController.scala
  app/controllers/SubmissionController.scala
  app/filters/ConfirmationFilter.scala
  test/connectors/AuthenticatorConnectorSpec.scala
  test/controllers/ConfirmationControllerSpec.scala
  test/controllers/StatusControllerSpec.scala
  test/controllers/SubmissionControllerSpec.scala
  test/filters/ConfirmationFilterSpec.scala
Labels: automation passing, build passing, pending QA, pending review

#756 Amls 4088 - Change Enrolment Model to TaxEnrolement
  app/audit/ESEnrolEvent.scala
  app/connectors/TaxEnrolmentsConnector.scala
  app/models/enrolment/TaxEnrolment.scala
  app/services/AuthEnrolmentsService.scala
  test/connectors/TaxEnrolmentsConnectorSpec.scala
  test/models/enrolment/TaxEnrolmentSpec.scala
  test/services/AuthEnrolmentsServiceSpec.scala
Labels: automation passing, build passing, pending QA, pending review

#759 Switch out mongo
  conf/application.conf
Labels: build passing, pending QA, pending review

#762 Add logging around status service and tax enrolments connector
  app/connectors/TaxEnrolmentsConnector.scala
  app/services/StatusService.scala
Labels: build passing, pending QA, pending review

#763 Add more debugging in landing controller
  app/controllers/LandingController.scala
Labels: build passing, pending QA, pending review

#764 Revert "Amls 4090 - Remove Refresh Profile and AuthenicatorConnector"
  app/connectors/AuthenticatorConnector.scala
  app/controllers/ConfirmationController.scala
  app/controllers/StatusController.scala
  app/controllers/SubmissionController.scala
  app/filters/ConfirmationFilter.scala
  test/connectors/AuthenticatorConnectorSpec.scala
  test/controllers/ConfirmationControllerSpec.scala
  test/controllers/StatusControllerSpec.scala
  test/controllers/SubmissionControllerSpec.scala
  test/filters/ConfirmationFilterSpec.scala
Labels: needs more work, pending QA, pending review

#758 AMLS-3468 | MDTP Only: New FX sub-sector to MSB Activities (MSB)
  app/controllers/msb/FXTransactionsInNext12MonthsController.scala
  app/controllers/msb/IdentifyLinkedTransactionsController.scala
  app/controllers/msb/MostTransactionsController.scala
  app/controllers/msb/SendMoneyToOtherCountryController.scala
  app/controllers/msb/SendTheLargestAmountsOfMoneyController.scala
  app/controllers/msb/WhatYouNeedController.scala
  app/controllers/msb/WhichCurrenciesController.scala
  app/controllers/msb/package.scala
  app/models/moneyservicebusiness/FXTransactionsInNext12Months.scala
  app/models/moneyservicebusiness/MoneyServiceBusiness.scala
  app/services/businessmatching/ServiceFlow.scala
  app/views/msb/fx_transaction_in_next_12_months.scala.html
  app/views/msb/summary.scala.html
  app/views/msb/what_you_need.scala.html
  app/views/tradingpremises/msb_services.scala.html
  app/views/tradingpremises/summary_details.scala.html
  conf/application.conf
  conf/messages
  conf/msb.routes
  test/controllers/RegistrationProgressControllerSpec.scala
  test/controllers/msb/FXTransactionsInNext12MonthsControllerSpec.scala
  test/controllers/msb/IdentifyLinkedTransactionsControllerSpec.scala
  test/controllers/msb/MostTransactionsControllerSpec.scala
  test/controllers/msb/SendMoneyToOtherCountryControllerSpec.scala
  test/controllers/msb/SendTheLargestAmountsOfMoneyControllerSpec.scala
  test/controllers/msb/SummaryControllerSpec.scala
  test/controllers/msb/WhatYouNeedControllerSpec.scala
  test/controllers/msb/WhichCurrencyControllerSpec.scala
  test/models/moneyservicebusiness/FXTransactionInNext12MonthsSpec.scala
  test/models/moneyservicebusiness/MoneyServiceBusinessSpec.scala
  test/services/UpdateSave4LaterServiceSpec.scala
  test/services/businessmatching/updateservice/ServiceFlowSpec.scala
  test/views/msb/fx_transaction_in_next_12_monthsSpec.scala
  test/views/msb/summarySpec.scala
  test/views/msb/what_you_needSpec.scala
Labels: build passing, pending QA, pending review
