Repository hmrc/amls-frontend, pull requests merged in 2018-08, with the labels that each got.

#760 Added new PR checklist
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement, pending review

#768 Enabled mongo in application config
  conf/application.conf
Labels: build passing

#767 AMLS-4026 | AMLS-4027 | Create new screen "How many foreign exchange transactions did you make in the last 12 months"
  app/controllers/renewal/FXTransactionsInLast12MonthsController.scala
  app/models/renewal/FXTransactionsInLast12Months.scala
  app/models/renewal/Renewal.scala
  app/services/RenewalService.scala
  app/views/renewal/fx_transaction_in_last_12_months.scala.html
  conf/messages
  conf/renewal.routes
  test/controllers/renewal/FXTransactionsInLast12MonthsControllerSpec.scala
  test/controllers/renewal/SummaryControllerSpec.scala
  test/models/renewal/FXTransactionsInLast12MonthsSpec.scala
  test/services/LandingServiceSpec.scala
  test/services/RenewalServiceSpec.scala
  test/views/renewal/fx_transactions_in_last_12_monthsSpec.scala
  test/views/renewal/summarySpec.scala
Labels: needs more work

#772 Bumped library versions according to service catalogue
  project/FrontendBuild.scala
  project/MicroService.scala
  project/plugins.sbt
Labels: pending review

#773 AMLS-4193 | Added hint text, unit tests and moved word count to left
  app/views/satisfaction_survey.scala.html
  conf/messages
  public/amls.css
  test/views/satisfaction_surveySpec.scala
Labels: build passing, pending review

#775 AMLS-4193 | Added Cache Buster to CSS
  app/views/include/main.scala.html
  app/views/include/main2.scala.html
Labels: build passing, pending review

#769 AMLS-4096 | Added FX to CYA page - Refactored Unit tests
  app/views/renewal/ce_transactions_in_last_12_months.scala.html
  app/views/renewal/fx_transaction_in_last_12_months.scala.html
  app/views/renewal/summary.scala.html
  conf/messages
  test/controllers/renewal/CETransactionsInLast12MonthsControllerSpec.scala
  test/controllers/renewal/FXTransactionsInLast12MonthsControllerSpec.scala
  test/controllers/renewal/SummaryControllerSpec.scala
  test/views/renewal/ce_transactions_in_last_12_monthsSpec.scala
  test/views/renewal/fx_transactions_in_last_12_monthsSpec.scala
  test/views/renewal/summarySpec.scala
Labels: pending review

#776 AMLS-4026 | AMLS-4194 | Ensure FX question data is applied to submission request
  app/models/renewal/Conversions.scala
  test/models/renewal/ConversionsSpec.scala
Labels: build passing, pending QA, reviewed

#774 AMLS-4026 | AMLS-4093 | Validate FX question is answered on renewal submission | AMLS-4195 | BUG- Renewal does not validate MSB Question TotalThroughput
  app/models/renewal/Renewal.scala
  app/services/RenewalService.scala
  test/services/LandingServiceSpec.scala
  test/services/RenewalServiceSpec.scala
Labels: build passing, pending QA, pending review

#777 Bumped library version according to service catalogue
  project/FrontendBuild.scala
Labels: build passing

#770 AMLS-4026 | AMLS-4191 | Add new screen "How many foreign exchange..." to renewal flow as specified in Scenarios 1-5
  app/controllers/renewal/FXTransactionsInLast12MonthsController.scala
  app/controllers/renewal/MostTransactionsController.scala
  app/controllers/renewal/SendMoneyToOtherCountryController.scala
  app/controllers/renewal/TotalThroughputController.scala
  app/controllers/renewal/WhichCurrenciesController.scala
  test/controllers/renewal/FXTransactionsInLast12MonthsControllerSpec.scala
  test/controllers/renewal/MostTransactionsControllerSpec.scala
  test/controllers/renewal/SendMoneyToOtherCountryControllerSpec.scala
  test/controllers/renewal/TotalThroughputControllerSpec.scala
  test/controllers/renewal/WhichCurrenciesControllerSpec.scala
Labels: build passing, pending QA

#779 HOTFIX: Remove cache from the right place on redirect
  app/controllers/LandingController.scala
  test/controllers/LandingControllerSpec.scala
Labels: reviewed

#781 AMLS-4219: Remove Save4Later cache entry on migration event
  app/connectors/cache/DataCacheConnectorMigrator.scala
  test/connectors/cache/DataCacheConnectorMigratorSpec.scala
Labels: build passing, pending QA, reviewed

#783 Amls 3884 - Clear section data when changing business activities for new submissions
  app/controllers/businessmatching/RegisterServicesController.scala
  test/controllers/businessmatching/RegisterServicesControllerSpec.scala
Labels: bug, build passing

#785 AMLS-4206 | Added a trailing slash to the responsible people indexed …
  conf/responsiblePeople.routes
  test/views/responsiblepeople/detailed_answersSpec.scala
Labels: bug, build passing

#786 AMLS-4265 Bug fix - content errors.
  conf/messages
Labels: bug, build passing, pending QA, pending review

#787 AMLS-4266 | BUG - With user XAML00000567894, submitting after adding and removing an incomplete responsible person causes scheme error
  app/controllers/responsiblepeople/RemoveResponsiblePersonController.scala
Labels: needs more work, pending QA, pending review

#788 AMLS-4266 | BUG - With user XAML00000567894, submitting after adding and removing an incomplete responsible person causes scheme error
  test/controllers/responsiblepeople/RemoveResponsiblePersonControllerSpec.scala
Labels: pending review
