Repository hmrc/amls-frontend, pull requests merged in 2019-01, with the labels that each got.

#885 AMLS-4547 | BUG FIX: Visually hidden text read: Has curly bracket zero curly bracket - no more
  app/views/responsiblepeople/legal_name.scala.html
Labels: build passing, pending review

#882 Amls 3564
  app/views/include/main.scala.html
  app/views/include/main2.scala.html
  app/views/include/notifications_your_messages.scala.html
  app/views/include/whatyouneed.scala.html
  conf/app.routes
  project/MicroService.scala
  project/plugins.sbt
Labels: reviewed

#889 Amls 4471 | Bug Fix: Fees table (accesibility)
  app/views/confirmation/breakdown.scala.html
  app/views/confirmation/confirmation_new.scala.html
Labels: build passing, reviewed

#898 Add config metrics
  app/config/ApplicationGlobal.scala
  conf/application.conf
Labels: pending review

#892 Amls 4383
  app/controllers/tradingpremises/WhatDoesYourBusinessDoController.scala
  test/controllers/tradingpremises/WhatDoesYourBusinessDoControllerSpec.scala
Labels: reviewed

#903 Amls 3551 master
  app/controllers/tradingpremises/ActivityStartDateController.scala
  app/controllers/tradingpremises/AgentCompanyDetailsController.scala
  app/controllers/tradingpremises/AgentCompanyNameController.scala
  app/controllers/tradingpremises/AgentNameController.scala
  app/controllers/tradingpremises/AgentPartnershipController.scala
  app/controllers/tradingpremises/BusinessStructureController.scala
  app/controllers/tradingpremises/DetailedAnswersController.scala
  app/controllers/tradingpremises/IsResidentialController.scala
  app/controllers/tradingpremises/MSBServicesController.scala
  app/controllers/tradingpremises/PremisesRegisteredController.scala
  app/controllers/tradingpremises/RegisteringAgentPremisesController.scala
  app/controllers/tradingpremises/RemoveTradingPremisesController.scala
  app/controllers/tradingpremises/WhatDoesYourBusinessDoController.scala
  app/controllers/tradingpremises/WhatYouNeedController.scala
  app/controllers/tradingpremises/WhereAreTradingPremisesController.scala
  app/controllers/tradingpremises/YourTradingPremisesController.scala
  app/models/tradingpremises/PremisesRegistered.scala
  app/models/tradingpremises/TradingPremises.scala
  app/views/tradingpremises/premises_registered.scala.html
  app/views/tradingpremises/summary.scala.html
  app/views/tradingpremises/summary_details.scala.html
  app/views/tradingpremises/what_you_need.scala.html
  app/views/tradingpremises/your_trading_premises.scala.html
  conf/messages
  conf/tradingPremises.routes
  public/amls.css
  test/controllers/FeeGuidanceControllerSpec.scala
  test/controllers/tradingpremises/ActivityStartDateControllerSpec.scala
  test/controllers/tradingpremises/AgentCompanyDetailsControllerSpec.scala
  test/controllers/tradingpremises/AgentCompanyNameControllerSpec.scala
  test/controllers/tradingpremises/AgentNameControllerSpec.scala
  test/controllers/tradingpremises/AgentPartnershipControllerSpec.scala
  test/controllers/tradingpremises/BusinessStructureControllerRelease7Spec.scala
  test/controllers/tradingpremises/BusinessStructureControllerSpec.scala
  test/controllers/tradingpremises/DetailedAnswersControllerSpec.scala
  test/controllers/tradingpremises/IsResidentialControllerSpec.scala
  test/controllers/tradingpremises/MSBServicesControllerSpec.scala
  test/controllers/tradingpremises/PremisesRegisteredControllerSpec.scala
  test/controllers/tradingpremises/RegisteringAgentPremisesControllerSpec.scala
  test/controllers/tradingpremises/RemoveTradingPremisesControllerSpec.scala
  test/controllers/tradingpremises/WhatDoesYourBusinessDoControllerSpec.scala
  test/controllers/tradingpremises/WhatYouNeedControllerSpec.scala
  test/controllers/tradingpremises/WhereAreTradingPremisesControllerSpec.scala
  test/controllers/tradingpremises/YourTradingPremisesControllerSpec.scala
  test/models/businessmatching/updateservice/TradingPremisesSpec.scala
  test/models/tradingpremises/PremisesRegisteredSpec.scala
  test/models/tradingpremises/TradingPremisesSpec.scala
  test/models/tradingpremises/YourTradingPremisesSpec.scala
  test/views/tradingpremises/premises_registeredSpec.scala
  test/views/tradingpremises/summary_detailsSpec.scala
  test/views/tradingpremises/your_trading_premisesSpec.scala
Labels: reviewed

#905 Amls 4639 - DI - Responsible People Controllers
  app/controllers/responsiblepeople/AdditionalExtraAddressController.scala
  app/controllers/responsiblepeople/ApprovalCheckController.scala
  app/controllers/responsiblepeople/AreTheyNominatedOfficerController.scala
  app/controllers/responsiblepeople/ContactDetailsController.scala
  app/controllers/responsiblepeople/CurrentAddressController.scala
  app/controllers/responsiblepeople/CurrentAddressDateOfChangeController.scala
  app/controllers/responsiblepeople/DetailedAnswersController.scala
  app/controllers/responsiblepeople/ExperienceTrainingController.scala
  app/controllers/responsiblepeople/NationalityController.scala
  app/controllers/responsiblepeople/PersonNameController.scala
  app/controllers/responsiblepeople/PositionWithinBusinessController.scala
  app/controllers/responsiblepeople/RegisteredForSelfAssessmentController.scala
  app/controllers/responsiblepeople/RemoveResponsiblePersonController.scala
  app/controllers/responsiblepeople/ResponsiblePeopleAddController.scala
  app/controllers/responsiblepeople/TimeAtAdditionalAddressController.scala
  app/controllers/responsiblepeople/TimeAtAdditionalExtraAddressController.scala
  app/controllers/responsiblepeople/TimeAtCurrentAddressController.scala
  app/controllers/responsiblepeople/VATRegisteredController.scala
  app/controllers/responsiblepeople/WhatYouNeedController.scala
  app/controllers/responsiblepeople/WhoMustRegisterController.scala
  app/controllers/responsiblepeople/YourResponsiblePeopleController.scala
  conf/responsiblePeople.routes
  test/controllers/responsiblepeople/AdditionalExtraAddressControllerSpec.scala
  test/controllers/responsiblepeople/ApprovalCheckControllerSpec.scala
  test/controllers/responsiblepeople/AreTheyNominatedOfficerControllerSpec.scala
  test/controllers/responsiblepeople/ContactDetailsControllerSpec.scala
  test/controllers/responsiblepeople/CurrentAddressControllerSpec.scala
  test/controllers/responsiblepeople/CurrentAddressDateOfChangeControllerSpec.scala
  test/controllers/responsiblepeople/DetailedAnswersControllerSpec.scala
  test/controllers/responsiblepeople/ExperienceTrainingControllerSpec.scala
  test/controllers/responsiblepeople/NationalityControllerSpec.scala
  test/controllers/responsiblepeople/PersonNameControllerSpec.scala
  test/controllers/responsiblepeople/PositionWithinBusinessControllerSpec.scala
  test/controllers/responsiblepeople/RegisteredForSelfAssessmentControllerSpec.scala
  test/controllers/responsiblepeople/RemoveResponsiblePersonControllerSpec.scala
  test/controllers/responsiblepeople/ResponsiblePersonAddControllerSpec.scala
  test/controllers/responsiblepeople/TimeAtAdditionalAddressControllerSpec.scala
  test/controllers/responsiblepeople/TimeAtAdditionalExtraAddressControllerSpec.scala
  test/controllers/responsiblepeople/TimeAtCurrentAddressControllerNoRelease7Spec.scala
  test/controllers/responsiblepeople/TimeAtCurrentAddressControllerSpec.scala
  test/controllers/responsiblepeople/VATRegisteredControllerSpec.scala
  test/controllers/responsiblepeople/WhatYouNeedControllerSpec.scala
  test/controllers/responsiblepeople/WhoMustRegisterControllerSpec.scala
  test/controllers/responsiblepeople/YourResponsiblePeopleControllerSpec.scala
Labels: pending QA

#906 Amls 4638 - bankdetails controllers DI refactor
  app/controllers/bankdetails/BankAccountIsUKController.scala
  app/controllers/bankdetails/BankAccountNameController.scala
  app/controllers/bankdetails/BankAccountTypeController.scala
  app/controllers/bankdetails/BankDetailsController.scala
  app/controllers/bankdetails/RemoveBankDetailsController.scala
  app/controllers/bankdetails/SummaryController.scala
  app/controllers/bankdetails/YourBankAccountsController.scala
  test/controllers/bankdetails/RemoveBankDetailsControllerSpec.scala
  test/controllers/bankdetails/SummaryControllerSpec.scala
  test/controllers/bankdetails/YourBankAccountsControllerSpec.scala
Labels: pending QA
