Repository hmrc/amls-frontend, pull requests merged in 2019-10, with the labels that each got.

#1198 New config for redirect to AMP svc
  app/config/ApplicationConfig.scala
  conf/application.conf
Labels: pending review

#1202 Add approval content for amp on approval screens in rp section
  conf/messages
  release_notes/AMLS-5343.txt
Labels: reviewed

#1201 Amls 5366 - Correct content 'pre application variation' P2
  app/views/businessmatching/updateservice/change_services.scala.html
  conf/app.routes
  conf/messages
  release_notes/AMLS-5366.txt
  test/views/businessmatching/updateservice/change_servicesSpec.scala
Labels: pending QA, pending review

#1200 Amls 4789 - Pre app content 1
  app/controllers/businessmatching/SummaryController.scala
  app/controllers/businessmatching/updateservice/AddBusinessTypeHelper.scala
  app/controllers/businessmatching/updateservice/add/AddBusinessTypeSummaryController.scala
  app/services/flowmanagement/pagerouters/businessmatching/updatetype/addflow/NoPSRPageRouter.scala
  app/views/businessmatching/updateservice/add/business_applied_for_psr_number.scala.html
  app/views/businessmatching/updateservice/add/cannot_add_services.scala.html
  app/views/businessmatching/updateservice/add/fit_and_proper.scala.html
  app/views/businessmatching/updateservice/add/msb_subservices.scala.html
  app/views/businessmatching/updateservice/add/select_activities.scala.html
  app/views/businessmatching/updateservice/add/update_services_summary.scala.html
  app/views/businessmatching/updateservice/add/what_do_you_do_here.scala.html
  conf/messages
  conf/updateService.routes
  release_notes/AMLS-4789.txt
  test/controllers/businessmatching/SummaryControllerSpec.scala
  test/controllers/businessmatching/updateservice/add/AddBusinessTypeSummaryControllerSpec.scala
  test/services/flowmanagement/flowrouters/AddMSBSpecificRouterSpec.scala
  test/utils/UpdateServicesSummaryFixtures.scala
  test/views/businessmatching/updateservice/add/cannot_add_servicesSpec.scala
  test/views/businessmatching/updateservice/add/select_activitiesSpec.scala
  test/views/businessmatching/updateservice/add/update_services_summarySpec.scala
Labels: pending QA, pending review

#1204 Amls 5367 - Correct content for pre app P3
  app/views/businessmatching/updateservice/add/add_more_activities.scala.html
  app/views/businessmatching/updateservice/add/new_service_information.scala.html
  app/views/businessmatching/updateservice/remove/need_more_information.scala.html
  conf/messages
  conf/updateService.routes
  release_notes/AMLS-5367.txt
  test/controllers/businessmatching/updateservice/remove/NeedMoreInformationControllerSpec.scala
  test/views/businessmatching/updateservice/add/new_service_informationSpec.scala
  test/views/businessmatching/updateservice/remove/need_more_informationSpec.scala
Labels: pending QA

#1210 AMLS-5412 | Update 'How do you want to pay your fees'
  app/views/payments/ways_to_pay.scala.html
  conf/messages
  release_notes/AMLS-5412.txt
  test/views/payments/ways_to_paySpec.scala
Labels: passed QA

#1211 Amls 5433 - MSB activities bug
  app/views/businessmatching/updateservice/add/msb_subservices.scala.html
  app/views/businessmatching/updateservice/add/what_do_you_do_here.scala.html
  conf/messages
  release_notes/AMLS-5433.txt
  test/views/businessmatching/updateservice/add/msb_subservicesSpec.scala
  test/views/businessmatching/updateservice/add/what_do_you_do_hereSpec.scala
Labels: pending QA

#1215 AMLS-5428 | Updated button text in pre-app variation
  app/controllers/businessmatching/updateservice/remove/WhatDateRemovedController.scala
  app/views/businessmatching/updateservice/add/business_applied_for_psr_number.scala.html
  app/views/businessmatching/updateservice/add/fit_and_proper.scala.html
  app/views/businessmatching/updateservice/add/msb_subservices.scala.html
  app/views/businessmatching/updateservice/add/select_activities.scala.html
  app/views/businessmatching/updateservice/add/trading_premises.scala.html
  app/views/businessmatching/updateservice/add/what_do_you_do_here.scala.html
  app/views/businessmatching/updateservice/add/which_fit_and_proper.scala.html
  app/views/businessmatching/updateservice/add/which_trading_premises.scala.html
  app/views/date_of_change.scala.html
  release_notes/AMLS-5428.txt
Labels: pending QA

#1221 Amls 5460 enhanced
  app/utils/AuthAction.scala
  app/views/unauthorised_role.scala.html
  release_notes/AMLS-5460.txt
  test/utils/AuthActionSpec.scala
Labels: Do-Not-Merge

#1208 AMLS-5168 | Removed ConfirmAddress in Responsible People
  app/controllers/responsiblepeople/ConfirmAddressController.scala
  app/controllers/responsiblepeople/ContactDetailsController.scala
  app/views/responsiblepeople/confirm_address.scala.html
  app/views/responsiblepeople/detailed_answers.scala.html
  conf/messages
  conf/responsiblePeople.routes
  release_notes/AMLS-5168.txt
  test/controllers/responsiblepeople/ConfirmAddressControllerSpec.scala
  test/controllers/responsiblepeople/ContactDetailsControllerSpec.scala
  test/views/responsiblepeople/confirm_addressSpec.scala
  test/views/responsiblepeople/detailed_answersSpec.scala
Labels: pending review

#1207 AMLS-5369 | Updated Fee & Ref content, added print link and GA tracking
  app/views/confirmation/confirm_amendvariation.scala.html
  app/views/confirmation/confirm_renewal.scala.html
  app/views/confirmation/confirmation_new.scala.html
  conf/messages
  public/print.css
  release_notes/AMLS-5369.txt
  test/controllers/ConfirmationControllerSpec.scala
  test/views/confirmation/AmendmentConfirmationViewSpec.scala
  test/views/confirmation/RenewalConfirmationViewSpec.scala
  test/views/confirmation/SubmitRegistrationConfirmationViewSpec.scala
Labels: pending QA

#1209 AMLS-5372 | Changed h1 for suspicious activities question
  conf/messages
  release_notes/AMLS-5372.txt
Labels: pending QA
