Repository hmrc/amls-frontend, pull requests merged in 2019-07, with the labels that each got.

#1109 Amls 4966 - Making Money service business questions editable
  app/controllers/msb/CETransactionsInNext12MonthsController.scala
  app/controllers/msb/ExpectedThroughputController.scala
  app/controllers/msb/FXTransactionsInNext12MonthsController.scala
  app/controllers/msb/MoneySourcesController.scala
  app/controllers/msb/SummaryController.scala
  app/controllers/msb/TransactionsInNext12MonthsController.scala
  app/controllers/msb/UsesForeignCurrenciesController.scala
  app/controllers/msb/WhichCurrenciesController.scala
  app/views/msb/summary.scala.html
  release_notes/AMLS-4966.txt
  test/controllers/msb/CETransactionsInNext12MonthsControllerSpec.scala
  test/controllers/msb/ExpectedThroughputControllerSpec.scala
  test/controllers/msb/FXTransactionsInNext12MonthsControllerSpec.scala
  test/controllers/msb/MoneySourcesControllerSpec.scala
  test/controllers/msb/SummaryControllerSpec.scala
  test/controllers/msb/TransactionsInNext12MonthsControllerSpec.scala
  test/controllers/msb/UsesForeignCurrenciesControllerSpec.scala
  test/controllers/msb/WhichCurrenciesControllerSpec.scala
  test/views/msb/summaryPreRelease7Spec.scala
  test/views/msb/summarySpec.scala
Labels: passed QA

#1110 Amls 4966 bug | AMLS-5160 - Uses foreign currencies dropping answers
  app/controllers/msb/UsesForeignCurrenciesController.scala
  app/controllers/renewal/UsesForeignCurrenciesController.scala
  release_notes/AMLS-4966-bug.txt
  test/controllers/msb/UsesForeignCurrenciesControllerSpec.scala
Labels: passed QA

#1111 AMLS-5120 | Implemented small RP content changes
  app/views/responsiblepeople/detailed_answers.scala.html
  app/views/responsiblepeople/experience_training.scala.html
  app/views/responsiblepeople/person_non_uk_passport.scala.html
  app/views/responsiblepeople/position_within_business_start_date.scala.html
  conf/messages
  release_notes/AMLS-5120.txt
  test/views/responsiblepeople/detailed_answersSpec.scala
Labels: passed QA

#1116 Amls 5133
  app/models/moneyservicebusiness/MoneyServiceBusiness.scala
  release_notes/AMLS-5133.txt
  test/models/moneyservicebusiness/MoneyServiceBusinessSpec.scala
Labels: passed QA

#1117 Fix incorrect error markup on TCSP flow
  app/views/tcsp/service_provider_types.scala.html
  app/views/tcsp/services_of_another_tcsp.scala.html
  release_notes/AMLS-5128.txt
Labels: passed QA

#1114 Amls 5125 - Conditional reveals not stacked correctly in Pre-app variation and amendment
  app/views/businessmatching/updateservice/add/business_applied_for_psr_number.scala.html
  app/views/businessmatching/updateservice/add/fit_and_proper.scala.html
  app/views/businessmatching/updateservice/add/trading_premises.scala.html
  release_notes/AMLS-5125.txt
Labels: pending QA

#1118 Amls 5016 - Questions editable in business activities
  app/controllers/businessactivities/ExpectedAMLSTurnoverController.scala
  app/controllers/businessactivities/ExpectedBusinessTurnoverController.scala
  app/controllers/businessactivities/InvolvedInOtherController.scala
  app/controllers/businessactivities/SummaryController.scala
  app/views/businessactivities/summary.scala.html
  release_notes/AMLS-5016.txt
  test/controllers/businessactivities/ExpectedAMLSTurnoverControllerSpec.scala
  test/controllers/businessactivities/ExpectedBusinessTurnoverControllerSpec.scala
  test/controllers/businessactivities/InvolvedInOtherControllerSpec.scala
  test/controllers/businessactivities/SummaryControllerSpec.scala
  test/views/businessactivities/summarySpec.scala
Labels: passed QA

#1119 AMLS-4926 | New error messages in EAB flow
  app/models/estateagentbusiness/PenalisedUnderEstateAgentsAct.scala
  app/models/estateagentbusiness/ProfessionalBody.scala
  app/models/estateagentbusiness/RedressScheme.scala
  conf/messages
  release_notes/AMLS-4926.txt
  test/models/estateagentbusiness/PenalisedUnderEstateAgentsActSpec.scala
  test/models/estateagentbusiness/ProfessionalBodySpec.scala
Labels: passed QA, reviewed

#1120 Amls 4992 - New error messages in Renewal flow
  app/models/renewal/CETransactionsInLast12Months.scala
  app/models/renewal/CustomersOutsideUK.scala
  app/models/renewal/FXTransactionsInLast12Months.scala
  app/models/renewal/MoneySources.scala
  app/models/renewal/PaymentMethods.scala
  app/models/renewal/SendTheLargestAmountsOfMoney.scala
  app/models/renewal/UsesForeignCurrencies.scala
  app/models/renewal/WhichCurrencies.scala
  conf/messages
  release_notes/AMLS-4992.txt
  test/controllers/renewal/SendTheLargestAmountsOfMoneyControllerSpec.scala
  test/models/renewal/CETransactionsInLast12MonthsSpec.scala
  test/models/renewal/FXTransactionsInLast12MonthsSpec.scala
  test/models/renewal/MoneySourcesSpec.scala
  test/models/renewal/PaymentMethodSpec.scala
  test/models/renewal/ReceiveCashPaymentsSpec.scala
  test/models/renewal/SendTheLargestAmountsOfMoneySpec.scala
  test/models/renewal/UsesForeignCurrenciesSpec.scala
Labels: passed QA

#1122 AMLS-5015 | Bug fix: HVD questions editable
  app/controllers/hvd/SummaryController.scala
  app/views/hvd/summary.scala.html
  release_notes/AMLS-5015.txt
  test/controllers/hvd/SummaryControllerSpec.scala
  test/views/hvd/summarySpec.scala
Labels: passed QA

#1121 Amls 5187 - Fix to redirection issues in MSB and Business Activities after making some questions editable
  app/controllers/businessactivities/WhatYouNeedController.scala
  app/controllers/msb/MostTransactionsController.scala
  app/controllers/msb/SendMoneyToOtherCountryController.scala
  app/controllers/msb/UsesForeignCurrenciesController.scala
  app/controllers/msb/WhatYouNeedController.scala
  release_notes/AMLS-5187.txt
  test/controllers/businessactivities/WhatYouNeedControllerSpec.scala
  test/controllers/msb/MostTransactionsControllerSpec.scala
  test/controllers/msb/SendMoneyToOtherCountryControllerSpec.scala
  test/controllers/msb/WhatYouNeedControllerSpec.scala
Labels: passed QA

#1123 Amls 4888 bugfix
  app/controllers/businessdetails/LettersAddressController.scala
  test/controllers/businessdetails/LettersAddressControllerSpec.scala
Labels: passed QA

#1115 Amls 4124 Split question in Renewal about €10,000 from customers not met in person
  app/controllers/renewal/CashPaymentsCustomersNotMetController.scala
  app/controllers/renewal/HowCashPaymentsReceivedController.scala
  app/controllers/renewal/PercentageOfCashPaymentOver15000Controller.scala
  app/controllers/renewal/ReceiveCashPaymentsController.scala
  app/models/hvd/ReceiveCashPayments.scala
  app/models/renewal/CashPayments.scala
  app/models/renewal/CashPaymentsCustomerNotMet.scala
  app/models/renewal/Conversions.scala
  app/models/renewal/HowCashPaymentsReceived.scala
  app/models/renewal/PaymentMethods.scala
  app/models/renewal/ReceiveCashPayments.scala
  app/models/renewal/Renewal.scala
  app/services/LandingService.scala
  app/views/renewal/cash_payments_customers_not_met.scala.html
  app/views/renewal/how_cash_payments_received.scala.html
  app/views/renewal/receiving.scala.html
  app/views/renewal/summary.scala.html
  conf/messages
  conf/renewal.routes
  release_notes/AMLS-4124.txt
  test/controllers/StatusControllerSpec.scala
  test/controllers/renewal/CashPaymentsCustomersNotMetControllerSpec.scala
  test/controllers/renewal/HowCashPaymentsReceivedControllerSpec.scala
  test/controllers/renewal/PercentageOfCashPaymentOver15000ControllerSpec.scala
  test/controllers/renewal/ReceiveCashPaymentsControllerSpec.scala
  test/controllers/renewal/SendMoneyToOtherCountryControllerSpec.scala
  test/controllers/renewal/SummaryControllerSpec.scala
  test/controllers/tradingpremises/RemoveTradingPremisesControllerSpec.scala
  test/models/hvd/ReceiveCashPaymentsSpec.scala
  test/models/renewal/CashPaymentsCustomerNotMetSpec.scala
  test/models/renewal/CashPaymentsSpec.scala
  test/models/renewal/ConversionsSpec.scala
  test/models/renewal/HowCashPaymentsReceivedSpec.scala
  test/models/renewal/PaymentMethodSpec.scala
  test/models/renewal/ReceiveCashPaymentsSpec.scala
  test/models/renewal/RenewalSpec.scala
  test/models/renewal/SendMoneyToOtherCountrySpec.scala
  test/services/LandingServiceSpec.scala
  test/services/RenewalServiceSpec.scala
  test/services/SubmissionServiceSpec.scala
  test/views/renewal/cash_payments_customers_not_metSpec.scala
  test/views/renewal/how_cash_payments_receivedSpec.scala
  test/views/renewal/receivingSpec.scala
  test/views/renewal/summarySpec.scala
Labels: passed QA

#1124 Amls 5142 - Making certain BM questions editable when pending approval
  app/views/businessmatching/summary.scala.html
  release_notes/AMLS-5142.txt
  test/controllers/businessmatching/SummaryControllerSpec.scala
Labels: pending QA

#1126 Amls 4998
  app/connectors/AmlsConnector.scala
  app/connectors/AmlsNotificationConnector.scala
  app/connectors/ConnectorHelper.scala
  app/connectors/FeeConnector.scala
  app/connectors/cache/DataCacheConnector.scala
  app/connectors/cache/MongoCacheConnector.scala
  app/controllers/DefaultBaseController.scala
  app/services/cache/MongoCacheClient.scala
  app/utils/AuthAction.scala
  app/utils/UrlHelper.scala
  conf/application.conf
  project/FrontendBuild.scala
  release_notes/AMLS-4998.txt
  test/connectors/ConnectorHelperSpec.scala
  test/connectors/cache/DataCacheConnectorSpec.scala
  test/connectors/cache/MongoCacheConnectorSpec.scala
  test/controllers/actions/MockedAuthActions.scala
  test/utils/AuthActionSpec.scala
  test/utils/UrlHelperSpec.scala
Labels: pending QA, pending review

#1125 Amls 5078 - New Auth for business activities
  app/connectors/AmlsConnector.scala
  app/controllers/businessactivities/AccountantForAMLSRegulationsController.scala
  app/controllers/businessactivities/BusinessFranchiseController.scala
  app/controllers/businessactivities/DocumentRiskAssessmentController.scala
  app/controllers/businessactivities/EmployeeCountAMLSSupervisionController.scala
  app/controllers/businessactivities/ExpectedAMLSTurnoverController.scala
  app/controllers/businessactivities/ExpectedBusinessTurnoverController.scala
  app/controllers/businessactivities/HowManyEmployeesController.scala
  app/controllers/businessactivities/IdentifySuspiciousActivityController.scala
  app/controllers/businessactivities/InvolvedInOtherController.scala
  app/controllers/businessactivities/NCARegisteredController.scala
  app/controllers/businessactivities/RiskAssessmentController.scala
  app/controllers/businessactivities/SummaryController.scala
  app/controllers/businessactivities/TaxMattersController.scala
  app/controllers/businessactivities/TransactionRecordController.scala
  app/controllers/businessactivities/TransactionTypesController.scala
  app/controllers/businessactivities/WhatYouNeedController.scala
  app/controllers/businessactivities/WhoIsYourAccountantController.scala
  app/services/AuthEnrolmentsService.scala
  app/services/SectionsProvider.scala
  app/services/StatusService.scala
  release_notes/AMLS-5078.txt
  test/controllers/RegistrationProgressControllerSpec.scala
  test/controllers/businessactivities/AccountantForAMLSRegulationsControllerSpec.scala
  test/controllers/businessactivities/BusinessFranchiseControllerSpec.scala
  test/controllers/businessactivities/DocumentRiskAssessmentPolicyControllerSpec.scala
  test/controllers/businessactivities/EmployeeCountAMLSSupervisionControllerSpec.scala
  test/controllers/businessactivities/ExpectedAMLSTurnoverControllerSpec.scala
  test/controllers/businessactivities/ExpectedBusinessTurnoverControllerSpec.scala
  test/controllers/businessactivities/HowManyEmployeesControllerSpec.scala
  test/controllers/businessactivities/IdentifiySuspiciousActivityControllerSpec.scala
  test/controllers/businessactivities/InvolvedInOtherControllerSpec.scala
  test/controllers/businessactivities/NCARegisteredControllerSpec.scala
  test/controllers/businessactivities/RiskAssessmentPolicyControllerSpec.scala
  test/controllers/businessactivities/SummaryControllerSpec.scala
  test/controllers/businessactivities/TaxMattersControllerSpec.scala
  test/controllers/businessactivities/TransactionRecordControllerSpec.scala
  test/controllers/businessactivities/TransactionTypesControllerSpec.scala
  test/controllers/businessactivities/WhatYouNeedControllerSpec.scala
  test/controllers/businessactivities/WhoIsYourAccountantControllerSpec.scala
  test/controllers/renewal/SummaryControllerSpec.scala
  test/services/StatusServiceSpec.scala
  test/utils/CacheMocks.scala
  test/utils/StatusMocks.scala
Labels: pending QA

#1128 AMLS-5116 | Countries error message bug
  app/controllers/msb/BranchesOrAgentsWhichCountriesController.scala
  release_notes/AMLS-5116.txt
Labels: pending QA

#1133 Amls 5214
  app/controllers/renewal/HowCashPaymentsReceivedController.scala
  app/models/renewal/CashPayments.scala
  release_notes/AMLS-5214.txt
  test/models/renewal/CashPaymentsSpec.scala
  test/models/renewal/RenewalSpec.scala
Labels: pending QA

#1132 AMLS-5214 Live bug fix customers outside uk
  app/models/renewal/Renewal.scala
  release_notes/AMLS-5214.txt
  test/models/renewal/RenewalSpec.scala
Labels: pending QA

#1135 Latest auth version
  project/FrontendBuild.scala
Labels: pending review

#1131 Release 4.456.0 release notes
  release_notes/AMLS-4124.txt
  release_notes/AMLS-4887.txt
  release_notes/AMLS-4888.txt
  release_notes/AMLS-4920.txt
  release_notes/AMLS-4923.txt
  release_notes/AMLS-4924.txt
  release_notes/AMLS-4926.txt
  release_notes/AMLS-4951.txt
  release_notes/AMLS-4966-bug.txt
  release_notes/AMLS-4966.txt
  release_notes/AMLS-4992.txt
  release_notes/AMLS-5015.txt
  release_notes/AMLS-5016.txt
  release_notes/AMLS-5101.txt
  release_notes/AMLS-5103.txt
  release_notes/AMLS-5110.txt
  release_notes/AMLS-5113.txt
  release_notes/AMLS-5116.txt
  release_notes/AMLS-5120.txt
  release_notes/AMLS-5121.txt
  release_notes/AMLS-5125.txt
  release_notes/AMLS-5128.txt
  release_notes/AMLS-5133.txt
  release_notes/AMLS-5142.txt
  release_notes/AMLS-5187.txt
  release_notes/AMLS-5214.txt
  release_notes/releases/v4.434.0-v4.458/v4.434.0-v4.458-25-07-2019.txt
Labels: pending review

#1136 Amls 5082 - Auth upgrades - Declaration flow
  app/controllers/declaration/AddPersonController.scala
  app/controllers/declaration/DeclarationController.scala
  app/controllers/declaration/RegisterPartnersController.scala
  app/controllers/declaration/RegisterResponsiblePersonController.scala
  app/controllers/declaration/WhoIsRegisteringController.scala
  app/controllers/declaration/WhoIsTheBusinessNominatedOfficerController.scala
  app/services/ProgressService.scala
  app/services/RenewalService.scala
  app/services/StatusService.scala
  app/utils/DeclarationHelper.scala
  release_notes/AMLS-5082.txt
  test/controllers/declaration/AddPersonControllerSpec.scala
  test/controllers/declaration/DeclarationControllerSpec.scala
  test/controllers/declaration/RegisterPartnersControllerSpec.scala
  test/controllers/declaration/RegisterResponsiblePersonControllerSpec.scala
  test/controllers/declaration/WhoIsRegisteringControllerSpec.scala
  test/controllers/declaration/WhoIsTheBusinessNominatedOfficerControllerSpec.scala
  test/utils/DependencyMocks.scala
Labels: pending QA

#1134 Amls 5076 - ASP auth upgrades
  app/connectors/cache/DataCacheConnector.scala
  app/controllers/asp/OtherBusinessTaxMattersController.scala
  app/controllers/asp/ServicesOfBusinessController.scala
  app/controllers/asp/ServicesOfBusinessDateOfChangeController.scala
  app/controllers/asp/SummaryController.scala
  app/controllers/asp/WhatYouNeedController.scala
  app/services/StatusService.scala
  app/services/businessmatching/BusinessMatchingService.scala
  app/services/businessmatching/ServiceFlow.scala
  release_notes/AMLS-4076.txt
  test/controllers/asp/OtherBusinessTaxMattersControllerSpec.scala
  test/controllers/asp/ServicesOfBusinessControllerSpec.scala
  test/controllers/asp/ServicesOfBusinessDateOfChangeControllerSpec.scala
  test/controllers/asp/SummaryControllerSpec.scala
  test/controllers/asp/WhatYouNeedControllerSpec.scala
  test/utils/ServiceFlowMocks.scala
Labels: pending QA

#1130 Amls 5186 - HVD: application can be submitted with missing payment date
  app/models/hvd/CashPayment.scala
  app/models/hvd/Hvd.scala
  release_notes/AMLS-5186.txt
  test/models/hvd/CashPaymentSpec.scala
  test/models/hvd/HvdSpec.scala
Labels: passed QA

#1138 AMLS-5079 | BusinessDetails Auth
  app/connectors/cache/DataCacheConnector.scala
  app/connectors/cache/MongoCacheConnector.scala
  app/controllers/businessdetails/ActivityStartDateController.scala
  app/controllers/businessdetails/ConfirmRegisteredOfficeController.scala
  app/controllers/businessdetails/ContactingYouController.scala
  app/controllers/businessdetails/ContactingYouPhoneController.scala
  app/controllers/businessdetails/CorporationTaxRegisteredController.scala
  app/controllers/businessdetails/CorrespondenceAddressIsUkController.scala
  app/controllers/businessdetails/CorrespondenceAddressNonUkController.scala
  app/controllers/businessdetails/CorrespondenceAddressUkController.scala
  app/controllers/businessdetails/LettersAddressController.scala
  app/controllers/businessdetails/PreviouslyRegisteredController.scala
  app/controllers/businessdetails/RegisteredOfficeDateOfChangeController.scala
  app/controllers/businessdetails/RegisteredOfficeIsUKController.scala
  app/controllers/businessdetails/RegisteredOfficeNonUKController.scala
  app/controllers/businessdetails/RegisteredOfficeUKController.scala
  app/controllers/businessdetails/SummaryController.scala
  app/controllers/businessdetails/VATRegisteredController.scala
  app/controllers/businessdetails/WhatYouNeedController.scala
  release_notes/AMLS-5079.txt
  test/controllers/businessdetails/ActivityStartDateControllerSpec.scala
  test/controllers/businessdetails/ConfirmRegisteredOfficeControllerSpec.scala
  test/controllers/businessdetails/ContactingYouControllerSpec.scala
  test/controllers/businessdetails/ContactingYouPhoneControllerSpec.scala
  test/controllers/businessdetails/CorporationTaxRegisteredControllerSpec.scala
  test/controllers/businessdetails/CorrespondenceAddressIsUkControllerSpec.scala
  test/controllers/businessdetails/CorrespondenceAddressNonUkControllerSpec.scala
  test/controllers/businessdetails/CorrespondenceAddressUkControllerSpec.scala
  test/controllers/businessdetails/LettersAddressControllerSpec.scala
  test/controllers/businessdetails/PreviouslyRegisteredControllerSpec.scala
  test/controllers/businessdetails/RegisteredOfficeDateOfChangeControllerSpec.scala
  test/controllers/businessdetails/RegisteredOfficeIsUKControllerSpec.scala
  test/controllers/businessdetails/RegisteredOfficeNonUKControllerSpec.scala
  test/controllers/businessdetails/RegisteredOfficeUKControllerSpec.scala
  test/controllers/businessdetails/SummaryControllerSpec.scala
  test/controllers/businessdetails/VATRegisteredControllerSpec.scala
  test/controllers/businessdetails/WhatYouNeedControllerSpec.scala
  test/utils/CacheMocksNewAuth.scala
Labels: pending review

#1139 Refactor cache id to reflect credId naming convention
  app/connectors/AmlsConnector.scala
  app/connectors/cache/DataCacheConnector.scala
  app/connectors/cache/MongoCacheConnector.scala
  app/controllers/asp/OtherBusinessTaxMattersController.scala
  app/controllers/asp/ServicesOfBusinessController.scala
  app/controllers/asp/ServicesOfBusinessDateOfChangeController.scala
  app/controllers/asp/SummaryController.scala
  app/controllers/bankdetails/BankAccountIsUKController.scala
  app/controllers/bankdetails/BankAccountNameController.scala
  app/controllers/bankdetails/BankAccountTypeController.scala
  app/controllers/bankdetails/HasBankAccountController.scala
  app/controllers/bankdetails/RemoveBankDetailsController.scala
  app/controllers/bankdetails/SummaryController.scala
  app/controllers/bankdetails/WhatYouNeedController.scala
  app/controllers/bankdetails/YourBankAccountsController.scala
  app/controllers/businessactivities/AccountantForAMLSRegulationsController.scala
  app/controllers/businessactivities/BusinessFranchiseController.scala
  app/controllers/businessactivities/DocumentRiskAssessmentController.scala
  app/controllers/businessactivities/EmployeeCountAMLSSupervisionController.scala
  app/controllers/businessactivities/ExpectedAMLSTurnoverController.scala
  app/controllers/businessactivities/ExpectedBusinessTurnoverController.scala
  app/controllers/businessactivities/HowManyEmployeesController.scala
  app/controllers/businessactivities/IdentifySuspiciousActivityController.scala
  app/controllers/businessactivities/InvolvedInOtherController.scala
  app/controllers/businessactivities/NCARegisteredController.scala
  app/controllers/businessactivities/RiskAssessmentController.scala
  app/controllers/businessactivities/SummaryController.scala
  app/controllers/businessactivities/TaxMattersController.scala
  app/controllers/businessactivities/TransactionRecordController.scala
  app/controllers/businessactivities/TransactionTypesController.scala
  app/controllers/businessactivities/WhoIsYourAccountantController.scala
  app/controllers/businessdetails/ActivityStartDateController.scala
  app/controllers/businessdetails/ConfirmRegisteredOfficeController.scala
  app/controllers/businessdetails/ContactingYouController.scala
  app/controllers/businessdetails/ContactingYouPhoneController.scala
  app/controllers/businessdetails/CorporationTaxRegisteredController.scala
  app/controllers/businessdetails/CorrespondenceAddressIsUkController.scala
  app/controllers/businessdetails/CorrespondenceAddressNonUkController.scala
  app/controllers/businessdetails/CorrespondenceAddressUkController.scala
  app/controllers/businessdetails/LettersAddressController.scala
  app/controllers/businessdetails/PreviouslyRegisteredController.scala
  app/controllers/businessdetails/RegisteredOfficeDateOfChangeController.scala
  app/controllers/businessdetails/RegisteredOfficeIsUKController.scala
  app/controllers/businessdetails/RegisteredOfficeNonUKController.scala
  app/controllers/businessdetails/RegisteredOfficeUKController.scala
  app/controllers/businessdetails/SummaryController.scala
  app/controllers/businessdetails/VATRegisteredController.scala
  app/controllers/declaration/AddPersonController.scala
  app/controllers/declaration/DeclarationController.scala
  app/controllers/declaration/RegisterPartnersController.scala
  app/controllers/declaration/RegisterResponsiblePersonController.scala
  app/controllers/declaration/WhoIsRegisteringController.scala
  app/controllers/declaration/WhoIsTheBusinessNominatedOfficerController.scala
  app/services/cache/MongoCacheClient.scala
  app/utils/AuthAction.scala
  app/utils/HttpResponseHelper.scala
  app/utils/MappingUtils.scala
  app/utils/OptionBindable.scala
  app/utils/RepeatingSection.scala
  app/utils/Strings.scala
Labels: pending review

#1129 Amls 5194 - AB Testing
  app/views/include/status/rightpanel_submissionreadyforreview.scala.html
  conf/messages
  release_notes/AMLS-5194.txt
  test/controllers/StatusControllerSpec.scala
  test/views/status/status_submittedSpec.scala
Labels: passed QA, pending review

#1140 Increasing test coverage
  app/controllers/businessmatching/updateservice/RemoveBusinessTypeHelper.scala
  app/controllers/changeofficer/Flow.scala
  app/models/renewal/Renewal.scala
  app/services/PaymentsService.scala
  release_notes/AMLS-0000.txt
  test/controllers/businessdetails/CorrespondenceAddressIsUkControllerSpec.scala
  test/controllers/businessmatching/updateservice/RemoveBusinessTypeHelperSpec.scala
  test/models/responsiblepeople/ResponsiblePersonSpec.scala
  test/services/ConfirmationServiceSpec.scala
  test/services/FeeResponseServiceSpec.scala
  test/services/PaymentsServiceSpec.scala
Labels: pending review
