Repository hmrc/amls-frontend, pull requests merged in 2019-09, with the labels that each got.

#1182 Update Auth use User in place of Admin
  app/utils/AuthAction.scala
  project/FrontendBuild.scala
  release_notes/AMLS-5309.txt
Labels: pending QA

#1183 add release notes
  release_notes/releases/v1.124.0/v1.124.0-05-09-2019.txt
Labels: pending review

#1187 AMLS-5308 | error pages changed to AMP
  app/config/ApplicationConfig.scala
  app/views/error.scala.html
  app/views/include/main.scala.html
  app/views/include/main2.scala.html
  app/views/include/notifications_your_messages.scala.html
  app/views/include/status/rightpanel_submissionreadyforreview.scala.html
  app/views/include/whatyouneed.scala.html
  app/views/submission/bad_request.scala.html
  app/views/submission/duplicate_enrolment.scala.html
  app/views/submission/duplicate_submission.scala.html
  app/views/submission/wrong_credential_type.scala.html
  conf/application.conf
  public/amls.css
  release_notes/AMLS-5308.txt
Labels: pending QA

#1190 AMLS-5297 | BUG-FIX: Editing business start date doesn't update trading premises section
  app/controllers/tradingpremises/ActivityStartDateController.scala
  release_notes/AMLS-5297.txt
  test/controllers/tradingpremises/ActivityStartDateControllerSpec.scala
Labels: reviewed

#1194 AMLS front end - landing controller data has changed for AMP
  app/controllers/LandingController.scala
  release_notes/AMLS-5282.txt
  test/controllers/LandingControllerWithAmendmentsSpec.scala
Labels: pending QA, pending review

#1196 Fixing warnings
  app/config/ApplicationConfig.scala
  app/models/ViewResponse.scala
  app/models/amp/Amp.scala
  app/models/asp/Asp.scala
  app/models/businessmatching/updateservice/UpdateService.scala
  app/models/estateagentbusiness/EstateAgentBusiness.scala
  app/models/hvd/Hvd.scala
  app/models/moneyservicebusiness/MoneyServiceBusiness.scala
  app/models/responsiblepeople/ResponsiblePerson.scala
  app/models/supervision/Supervision.scala
  app/models/tcsp/Tcsp.scala
  app/models/tradingpremises/TradingPremises.scala
  test/models/amp/AmpSpec.scala
Labels: pending QA, pending review

#1197 Change the url of AMP FE to be more seamless to the user
  app/config/ApplicationConfig.scala
  conf/application.conf
  release_notes/AMLS-5355.txt
Labels: pending QA, pending review
