Repository hmrc/amls-frontend, pull requests merged in 2019-03, with the labels that each got.

#952 Amls 4715 | EAB content changes
  app/views/estateagentbusiness/business_servicess.scala.html
  conf/estateAgents.routes
  conf/messages
  release_notes/AMLS-4715.txt
Labels: build passing, passed QA

#953 Amls 4670 | TP content changes
  app/views/tradingpremises/activity_start_date.scala.html
  app/views/tradingpremises/where_are_trading_premises.scala.html
  conf/messages
  release_notes/AMLS-4670.txt
  test/views/tradingpremises/activit_start_dateSpec.scala
Labels: build passing, pending QA

#963 Amls 4627
  app/controllers/changeofficer/Flow.scala
  app/controllers/changeofficer/FurtherUpdatesController.scala
  app/controllers/changeofficer/NewOfficerController.scala
  app/controllers/tradingpremises/RemoveTradingPremisesController.scala
  app/models/changeofficer/FurtherUpdates.scala
  app/views/changeofficer/further_updates.scala.html
  app/views/estateagentbusiness/business_servicess.scala.html
  app/views/tradingpremises/activity_start_date.scala.html
  app/views/tradingpremises/remove_trading_premises.scala.html
  app/views/tradingpremises/where_are_trading_premises.scala.html
  conf/app.routes
  conf/estateAgents.routes
  conf/messages
  conf/tradingPremises.routes
  release_notes/AMLS-4627.txt
  release_notes/AMLS-4670.txt
  release_notes/AMLS-4715.txt
  release_notes/AMLS-4752.txt
  test/controllers/changeofficer/FurtherUpdatesControllerSpec.scala
  test/controllers/changeofficer/NewOfficerControllerSpec.scala
  test/controllers/tradingpremises/RemoveTradingPremisesControllerSpec.scala
  test/models/changeofficer/FurtherUpdatesSpec.scala
  test/views/changeofficer/further_updatesSpec.scala
  test/views/tradingpremises/activit_start_dateSpec.scala
  test/views/tradingpremises/remove_trading_premisesSpec.scala
Labels: pending QA

#960 AMLS-4740 | DI Updates
  app/config/ApplicationConfig.scala
  app/config/ApplicationGlobal.scala
  app/config/Wiring.scala
  app/connectors/GovernmentGatewayConnector.scala
  app/controllers/AmlsController.scala
  app/controllers/ConfirmationController.scala
  app/controllers/LandingController.scala
  app/controllers/RegistrationProgressController.scala
  app/controllers/SatisfactionSurveyController.scala
  app/controllers/StatusController.scala
  app/controllers/SubmissionController.scala
  app/controllers/bankdetails/BankAccountIsUKController.scala
  app/controllers/bankdetails/BankAccountTypeController.scala
  app/controllers/bankdetails/RemoveBankDetailsController.scala
  app/controllers/bankdetails/YourBankAccountsController.scala
  app/controllers/businessmatching/SummaryController.scala
  app/controllers/msb/MostTransactionsController.scala
  app/controllers/msb/SendTheLargestAmountsOfMoneyController.scala
  app/controllers/supervision/PenalisedByProfessionalController.scala
  app/controllers/supervision/ProfessionalBodyMemberController.scala
  app/controllers/supervision/WhichProfessionalBodyController.scala
  app/controllers/testonly/TestOnlyController.scala
  app/modules/Module.scala
  app/services/cache/MongoCacheClient.scala
  conf/app.routes
  release_notes/AMLS-4740.txt
  test/connectors/BusinessMatchingConnectorSpec.scala
  test/connectors/GovernmentGatewayConnectorSpec.scala
  test/controllers/AmlsControllerSpec.scala
Labels: passed QA, reviewed

#959 Amls 4451 - changed contents for RP removal
  app/controllers/responsiblepeople/RemoveResponsiblePersonController.scala
  app/controllers/tradingpremises/RemoveTradingPremisesController.scala
  app/views/changeofficer/remove_responsible_person.scala.html
  app/views/responsiblepeople/remove_responsible_person.scala.html
  app/views/tradingpremises/remove_trading_premises.scala.html
  conf/messages
  conf/tradingPremises.routes
  release_notes/AMLS-4451.txt
  release_notes/AMLS-4627.txt
  test/controllers/tradingpremises/RemoveTradingPremisesControllerSpec.scala
  test/views/changeofficer/remove_responsible_personSpec.scala
  test/views/include/headingSpec.scala
  test/views/include/headingWithPlaceholderSpec.scala
  test/views/responsiblepeople/remove_responsible_personSpec.scala
  test/views/tradingpremises/remove_trading_premisesSpec.scala
Labels: pending QA

#964 Amls 3776
  conf/application.conf
  release_notes/AMLS-3776.txt
Labels: passed QA, reviewed

#958 Amls 4658 - Updated content and contractions in Business Activities section
  app/controllers/businessactivities/ExpectedAMLSTurnoverController.scala
  app/controllers/businessactivities/InvolvedInOtherController.scala
  app/controllers/businessactivities/TaxMattersController.scala
  app/utils/ControllerHelper.scala
  app/views/businessactivities/expected_amls_turnover.scala.html
  app/views/businessactivities/involved_in_other_name.scala.html
  app/views/businessactivities/nca_registered.scala.html
  app/views/businessactivities/summary.scala.html
  app/views/businessactivities/tax_matters.scala.html
  app/views/businessactivities/who_is_your_accountant.scala.html
  conf/messages
  release_notes/AMLS-4658.txt
  test/controllers/businessactivities/InvolvedInOtherControllerSpec.scala
  test/controllers/businessactivities/TaxMattersControllerSpec.scala
  test/utils/ControllerHelperSpec.scala
  test/views/businessactivities/summarySpec.scala
  test/views/businessactivities/tax_mattersSpec.scala
Labels: pending QA

#967 AMLS-4754 | Updated Countries and Currencies pages
  app/views/msb/branches_or_agents.scala.html
  app/views/msb/most_transactions.scala.html
  app/views/msb/send_largest_amounts_of_money.scala.html
  app/views/renewal/customers_outside_uk.scala.html
  app/views/renewal/most_transactions.scala.html
  app/views/renewal/send_largest_amounts_of_money.scala.html
  conf/messages
  public/amls.js
  public/autocomplete/location-autocomplete.min.js
  release_notes/AMLS-4754.txt
Labels: passed QA, reviewed

#971 AMLS-4272 | Added unique tags for edit links on Check Your Answers Page
  app/views/supervision/summary.scala.html
Labels: pending review

#969 AMLS-4603 | Bug fix
  app/controllers/supervision/ProfessionalBodyMemberController.scala
  release_notes/AMLS-4603.txt
  test/controllers/supervision/ProfessionalBodyMemberControllerSpec.scala
Labels: passed QA, reviewed

#978 Generated v4.286.0 release notes
  release_notes/AMLS-4272.txt
  release_notes/AMLS-4603.txt
  release_notes/AMLS-4754.txt
  release_notes/AMLS-4759.txt
  release_notes/releases/v4.286.0/-19-03-2019.txt
Labels: reviewed

#977 AMLS-4716 | Content updates on Declaration / Submission
  app/views/confirmation/confirm_amendvariation.scala.html
  app/views/confirmation/confirm_renewal.scala.html
  app/views/confirmation/confirmation_new.scala.html
  app/views/declaration/select_business_nominated_officer.scala.html
  app/views/declaration/who_is_registering_common.scala.html
  app/views/declaration/who_is_registering_this_registration.scala.html
  app/views/declaration/who_is_registering_this_renewal.scala.html
  app/views/declaration/who_is_registering_this_update.scala.html
  app/views/payments/bank_details.scala.html
  app/views/payments/ways_to_pay.scala.html
  conf/messages
  release_notes/AMLS-4716.txt
  test/views/confirmation/BacsConfirmationTransitionalRenewalViewSpec.scala
  test/views/confirmation/BacsConfirmationViewSpec.scala
  test/views/confirmation/PaymentConfirmedTransitionalRenewalViewSpec.scala
  test/views/confirmation/PaymentConfirmedViewSpec.scala
  test/views/confirmation/SubmitRegistrationConfirmationViewSpec.scala
  test/views/payments/bank_detailsSpec.scala
Labels: passed QA, reviewed

#979 update release note gen to prompt for tag
  generate-release-notes.sh
Labels: pending review

#974 Amls 4757
  conf/messages
  release_notes/AMLS-4757.txt
Labels: pending QA, reviewed

#970 AMLS 4733 | Removed showFees toggle
  app/config/ApplicationConfig.scala
  app/controllers/FeeGuidanceController.scala
  app/controllers/declaration/WhoIsTheBusinessNominatedOfficerController.scala
  app/controllers/responsiblepeople/DetailedAnswersController.scala
  app/controllers/responsiblepeople/FitAndProperController.scala
  app/controllers/responsiblepeople/FitAndProperNoticeController.scala
  app/services/ProgressService.scala
  app/utils/DeclarationHelper.scala
  app/views/responsiblepeople/fit_and_proper.scala.html
  app/views/responsiblepeople/fit_and_proper_notice.scala.html
  conf/app.routes
  conf/application.conf
  release_notes/AMLS-4733.txt
  test/controllers/FeeGuidanceControllerSpec.scala
  test/controllers/declaration/RegisterPartnersControllerSpec.scala
  test/controllers/declaration/WhoIsTheBusinessNominatedOfficerControllerSpec.scala
  test/controllers/renewal/RenewalProgressControllerSpec.scala
  test/services/ProgressServiceSpec.scala
  test/views/responsiblepeople/fit_and_properSpec.scala
Labels: passed QA, pending QA

#981 AMLS-4796 | Supervision bug fix
  app/controllers/supervision/SummaryController.scala
  app/utils/ControllerHelper.scala
  app/views/supervision/summary.scala.html
  release_notes/AMLS-4796.txt
  test/controllers/supervision/SummaryControllerSpec.scala
  test/utils/ControllerHelperSpec.scala
Labels: passed QA, reviewed

#983 Remove address from URL string when removing trading premises
  app/controllers/tradingpremises/RemoveTradingPremisesController.scala
  app/views/tradingpremises/remove_trading_premises.scala.html
  conf/tradingPremises.routes
  release_notes/AMLS-4799.txt
  test/controllers/tradingpremises/RemoveTradingPremisesControllerSpec.scala
Labels: passed QA, reviewed

#982 Generated release notes for release 4.296.0
  release_notes/AMLS-4272.txt
  release_notes/AMLS-4603.txt
  release_notes/AMLS-4716.txt
  release_notes/AMLS-4733.txt
  release_notes/AMLS-4754.txt
  release_notes/AMLS-4757.txt
  release_notes/AMLS-4758.txt
  release_notes/AMLS-4759.txt
  release_notes/AMLS-4770.txt
  release_notes/AMLS-4796.txt
  release_notes/releases/v4.296.0/v4.296.0-20-03-2019.txt
Labels: pending review

#984 Amls 4818
  conf/messages
  release_notes/AMLS-4818.txt
Labels: passed QA, pending QA

#985 Amls 4515
  app/controllers/RegistrationProgressController.scala
  app/views/include/forms2/submit.scala.html
  app/views/include/registration_progress_sidebar.scala.html
  app/views/include/submit_application.scala.html
  app/views/registrationamendment/registration_amendment.scala.html
  app/views/registrationamendment/section.scala.html
  app/views/registrationamendment/section_list.scala.html
  app/views/registrationprogress/registration_progress.scala.html
  app/views/registrationprogress/section.scala.html
  app/views/renewal/application_submit.scala.html
  app/views/renewal/renewal_progress.scala.html
  conf/messages
  public/amls.css
  release_notes/AMLS-4515.txt
  test/controllers/RegistrationProgressControllerSpec.scala
  test/controllers/renewal/RenewalProgressControllerSpec.scala
  test/views/include/submit_applicationSpec.scala
  test/views/registrationamendment/registration_amendmentSpec.scala
  test/views/registrationprogress/registration_progressSpec.scala
  test/views/registrationprogress/sectionSpec.scala
  test/views/renewal/application_submitSpec.scala
  test/views/renewal/renewal_progressSpec.scala
Labels: pending QA

#986 Amls 4123 - Which Currencies page split
  app/controllers/msb/FXTransactionsInNext12MonthsController.scala
  app/controllers/msb/MoneySourcesController.scala
  app/controllers/msb/UsesForeignCurrenciesController.scala
  app/controllers/msb/WhichCurrenciesController.scala
  app/models/moneyservicebusiness/MoneySource.scala
  app/models/moneyservicebusiness/MoneySources.scala
  app/models/moneyservicebusiness/UsesForeignCurrencies.scala
  app/models/moneyservicebusiness/WhichCurrencies.scala
  app/models/renewal/WhichCurrencies.scala
  app/services/LandingService.scala
  app/views/msb/money_sources.scala.html
  app/views/msb/summary.scala.html
  app/views/msb/uses_foreign_currencies.scala.html
  app/views/msb/which_currencies.scala.html
  conf/messages
  conf/msb.routes
  release_notes/AMLS-4123.txt
  test/controllers/msb/CETransactionsInNext12MonthsControllerSpec.scala
  test/controllers/msb/FXTransactionsInNext12MonthsControllerSpec.scala
  test/controllers/msb/MoneySourcesControllerSpec.scala
  test/controllers/msb/SummaryControllerSpec.scala
  test/controllers/msb/UsesForeignCurrenciesControllerSpec.scala
  test/controllers/msb/WhichCurrenciesControllerSpec.scala
  test/controllers/msb/WhichCurrencyControllerSpec.scala
  test/models/moneyservicebusiness/MoneyServiceBusinessSpec.scala
  test/models/moneyservicebusiness/MoneySourcesSpec.scala
  test/models/moneyservicebusiness/UsesForeignCurrenciesSpec.scala
  test/models/moneyservicebusiness/WhichCurrenciesSpec.scala
  test/models/renewal/ConversionsSpec.scala
  test/services/LandingServiceSpec.scala
  test/services/UpdateMongoCacheServiceSpec.scala
  test/views/msb/money_sourcesSpec.scala
  test/views/msb/summaryPreRelease7Spec.scala
  test/views/msb/summarySpec.scala
  test/views/msb/uses_foreign_currenciesSpec.scala
  test/views/msb/which_currenciesSpec.scala
Labels: pending QA
