Repository hmrc/amls-frontend, pull requests merged in 2019-05, with the labels that each got.

#1023 Amls 3763 - Updates to content in pre-application flow
  app/controllers/businessmatching/RegisterServicesController.scala
  app/views/businessmatching/register_services.scala.html
  app/views/businessmatching/services.scala.html
  app/views/businessmatching/summary.scala.html
  conf/businessMatching.routes
  conf/messages
  release_notes/AMLS-3763.txt
  test/controllers/businessmatching/RegisterServicesControllerSpec.scala
  test/views/businessmatching/register_servicesSpec.scala
  test/views/businessmatching/servicesSpec.scala
  test/views/businessmatching/summarySpec.scala
Labels: passed QA

#1031 Fix typo in PSR question
  conf/businessMatching.routes
Labels: pending QA, pending review

#1022 AMLS-4910: Add h1 to legend for EAB
  app/views/estateagentbusiness/business_servicess.scala.html
  app/views/estateagentbusiness/penalised_by_professional.scala.html
  app/views/estateagentbusiness/penalised_under_estate_agents_act.scala.html
  app/views/estateagentbusiness/redress_scheme.scala.html
  app/views/include/forms2/fieldset.scala.html
  release_notes/AMLS-4910.txt
Labels: build passing, passed QA

#1028 Amls 4767
  app/controllers/hvd/ProductsController.scala
  app/models/hvd/Products.scala
  app/views/hvd/cash_payment.scala.html
  app/views/hvd/expect_to_receive.scala.html
  app/views/hvd/how_will_you_sell_goods.scala.html
  app/views/hvd/products.scala.html
  app/views/hvd/summary.scala.html
  app/views/hvd/what_you_need.scala.html
  conf/hvd.routes
  conf/messages
  release_notes/AMLS-4767.txt
  test/models/hvd/ProductsSpec.scala
  test/views/hvd/summarySpec.scala
Labels: passed QA

#1025 Amls 4774
  app/views/include/status/before_you_go.scala.html
  app/views/include/status/rightpanel_incomplete.scala.html
  app/views/include/status/rightpanel_renewalincomplete.scala.html
  app/views/include/status/rightpanel_renewalnotsubmitted.scala.html
  app/views/include/status/rightpanel_renewalsubmitted.scala.html
  app/views/include/status/rightpanel_submissionreadyforreview.scala.html
  app/views/status/status_incomplete.scala.html
  app/views/status/status_not_submitted.scala.html
  app/views/status/status_renewal_incomplete.scala.html
  app/views/status/status_renewal_not_submitted.scala.html
  app/views/status/status_renewal_submitted.scala.html
  app/views/status/status_submitted.scala.html
  app/views/status/status_supervised.scala.html
  conf/messages
  public/amls.css
  release_notes/AMLS-4774.txt
  test/controllers/StatusControllerSpec.scala
  test/views/status/status_incompleteSpec.scala
  test/views/status/status_not_submittedSpec.scala
  test/views/status/status_renewal_incompleteSpec.scala
  test/views/status/status_renewal_not_submittedSpec.scala
  test/views/status/status_renewal_submittedSpec.scala
  test/views/status/status_submittedSpec.scala
  test/views/status/status_supervisedSpec.scala
Labels: passed QA

#1029 AMLS-4832 | Adding business name and services to renewal
  app/controllers/renewal/RenewalProgressController.scala
  app/views/include/services_sidebar.scala.html
  app/views/registrationamendment/registration_amendment.scala.html
  app/views/registrationprogress/registration_progress.scala.html
  app/views/renewal/renewal_progress.scala.html
  release_notes/AMLS-4832.txt
  test/views/registrationprogress/registration_progressSpec.scala
  test/views/renewal/renewal_progressSpec.scala
Labels: passed QA

#1026 Amls 4886
  app/views/bankdetails/bank_account_is_uk.scala.html
  app/views/businessactivities/business_franchise_name.scala.html
  app/views/businessactivities/involved_in_other_name.scala.html
  app/views/businessactivities/risk_assessment_policy.scala.html
  app/views/businessdetails/previously_registered.scala.html
  app/views/businessdetails/vat_registered.scala.html
  app/views/businessmatching/psr_number.scala.html
  app/views/estateagentbusiness/penalised_by_professional.scala.html
  app/views/estateagentbusiness/penalised_under_estate_agents_act.scala.html
  app/views/msb/branches_or_agents.scala.html
  app/views/msb/business_use_an_ipsp.scala.html
  app/views/renewal/customers_outside_uk.scala.html
  app/views/renewal/involved_in_other.scala.html
  app/views/renewal/receiving.scala.html
  app/views/responsiblepeople/country_of_birth.scala.html
  app/views/responsiblepeople/experience_training.scala.html
  app/views/responsiblepeople/known_by.scala.html
  app/views/responsiblepeople/legal_name.scala.html
  app/views/responsiblepeople/person_non_uk_passport.scala.html
  app/views/responsiblepeople/person_residence_type.scala.html
  app/views/responsiblepeople/person_uk_passport.scala.html
  app/views/responsiblepeople/registered_for_self_assessment.scala.html
  app/views/responsiblepeople/training.scala.html
  app/views/responsiblepeople/vat_registered.scala.html
  app/views/supervision/another_body.scala.html
  app/views/supervision/penalised_by_professional.scala.html
  app/views/tcsp/another_tcsp_supervision.scala.html
  app/views/tcsp/complex_corp_structure_creation.scala.html
  app/views/tcsp/only_off_the_shelf_comps_sold.scala.html
  app/views/tcsp/services_of_another_tcsp.scala.html
  public/amls.css
  release_notes/AMLS-4886.txt
Labels: passed QA

#1032 AMLS-4980 - update to the pay your fees message
  conf/messages
Labels: passed QA

#1030 AMLS-4921: Add h1 to legend for renewal flow
  app/utils/HtmlElementHelpers.scala
  app/views/businessactivities/business_employees.scala.html
  app/views/businessactivities/business_employees_amls_supervision.scala.html
  app/views/estateagentbusiness/business_servicess.scala.html
  app/views/include/forms2/date.scala.html
  app/views/include/forms2/input.scala.html
  app/views/msb/ce_transaction_in_next_12_months.scala.html
  app/views/msb/fx_transaction_in_next_12_months.scala.html
  app/views/msb/transactions_in_next_12_months.scala.html
  app/views/renewal/amls_turnover.scala.html
  app/views/renewal/business_turnover.scala.html
  app/views/renewal/ce_transactions_in_last_12_months.scala.html
  app/views/renewal/customers_outside_uk.scala.html
  app/views/renewal/fx_transaction_in_last_12_months.scala.html
  app/views/renewal/involved_in_other.scala.html
  app/views/renewal/money_sources.scala.html
  app/views/renewal/most_transactions.scala.html
  app/views/renewal/percentage.scala.html
  app/views/renewal/receiving.scala.html
  app/views/renewal/send_largest_amounts_of_money.scala.html
  app/views/renewal/send_money_to_other_country.scala.html
  app/views/renewal/total_throughput.scala.html
  app/views/renewal/uses_foreign_currencies.scala.html
  app/views/renewal/which_currencies.scala.html
  public/amls.css
  release_notes/AMLS-4921.txt
  test/views/renewal/total_throughputSpec.scala
Labels: passed QA

#1027 Amls 4957
  app/controllers/RegistrationProgressController.scala
  release_notes/AMLS-4957.txt
  test/controllers/RegistrationProgressControllerSpec.scala
Labels: passed QA

#1034 Amls 4917 - Error removing BPS or TDI
  app/controllers/businessmatching/updateservice/RemoveBusinessTypeHelper.scala
  test/controllers/businessmatching/updateservice/RemoveBusinessTypeHelperSpec.scala
Labels: passed QA

#1036 AMLS-4989: EAB and Renewal markup/accessibility fixes
  app/views/estateagentbusiness/penalised_by_professional.scala.html
  app/views/estateagentbusiness/penalised_under_estate_agents_act.scala.html
  app/views/estateagentbusiness/redress_scheme.scala.html
  app/views/include/forms2/country_autocomplete.scala.html
  app/views/include/forms2/currency.scala.html
  app/views/include/forms2/input.scala.html
  app/views/include/forms2/panel.scala.html
  app/views/include/forms2/textarea.scala.html
  app/views/renewal/ce_transactions_in_last_12_months.scala.html
  app/views/renewal/fx_transaction_in_last_12_months.scala.html
  app/views/renewal/involved_in_other.scala.html
  app/views/renewal/money_sources.scala.html
  app/views/renewal/percentage.scala.html
  app/views/renewal/receiving.scala.html
  app/views/renewal/total_throughput.scala.html
  app/views/renewal/transactions_in_last_12_months.scala.html
  app/views/renewal/uses_foreign_currencies.scala.html
  app/views/renewal/which_currencies.scala.html
  release_notes/AMLS-4989.txt
  test/views/renewal/transactions_in_last_12_monthsSpec.scala
Labels: passed QA

#1035 Amls 4927 - renewal flow error messages
  app/models/renewal/InvolvedInOther.scala
  conf/messages
  release_notes/AMLS-4927.txt
  test/models/renewal/InvolvedInOtherSpec.scala
Labels: passed QA

#1038 Amls 4838 - Bug fix: Validation error messages not linked to group on MSB 'Where do you send the largest amounts of money' page
  app/models/moneyservicebusiness/SendTheLargestAmountsOfMoney.scala
  app/models/renewal/SendTheLargestAmountsOfMoney.scala
  app/services/LandingService.scala
  app/views/msb/send_largest_amounts_of_money.scala.html
  app/views/msb/summary.scala.html
  release_notes/AMLS-4838.txt
  test/controllers/msb/SendMoneyToOtherCountryControllerSpec.scala
  test/controllers/msb/SendTheLargestAmountsOfMoneyControllerSpec.scala
  test/controllers/msb/SummaryControllerSpec.scala
  test/models/moneyservicebusiness/MoneyServiceBusinessSpec.scala
  test/models/moneyservicebusiness/SendTheLargestAmountsOfMoneySpec.scala
  test/models/renewal/ConversionsSpec.scala
  test/services/LandingServiceSpec.scala
  test/services/UpdateMongoCacheServiceSpec.scala
  test/views/msb/send_largest_amounts_of_moneySpec.scala
  test/views/msb/summarySpec.scala
Labels: passed QA

#1040 AMLS-4915: Add h1 to legend for Business Activities
  app/views/businessactivities/accountant_for_amls_regulations.scala.html
  app/views/businessactivities/business_employees.scala.html
  app/views/businessactivities/business_employees_amls_supervision.scala.html
  app/views/businessactivities/business_franchise_name.scala.html
  app/views/businessactivities/customer_transaction_records.scala.html
  app/views/businessactivities/expected_amls_turnover.scala.html
  app/views/businessactivities/expected_business_turnover.scala.html
  app/views/businessactivities/identify_suspicious_activity.scala.html
  app/views/businessactivities/involved_in_other_name.scala.html
  app/views/businessactivities/nca_registered.scala.html
  app/views/businessactivities/risk_assessment_policy.scala.html
  app/views/businessactivities/tax_matters.scala.html
  app/views/businessactivities/transaction_types.scala.html
  app/views/businessactivities/who_is_your_accountant.scala.html
  conf/messages
  release_notes/AMLS-4915.txt
Labels: passed QA

#1037 Amls 4928 - Content changes
  app/controllers/businessactivities/ExpectedAMLSTurnoverController.scala
  app/controllers/businessactivities/InvolvedInOtherController.scala
  app/controllers/businessactivities/SummaryController.scala
  app/controllers/renewal/InvolvedInOtherController.scala
  app/models/businessmatching/BusinessMatching.scala
  app/views/bankdetails/bank_account_types.scala.html
  app/views/bankdetails/what_you_need.scala.html
  app/views/businessactivities/expected_amls_turnover.scala.html
  app/views/businessactivities/involved_in_other_name.scala.html
  app/views/businessactivities/summary.scala.html
  app/views/businessactivities/what_you_need.scala.html
  app/views/businessdetails/what_you_need.scala.html
  app/views/estateagentbusiness/redress_scheme.scala.html
  app/views/estateagentbusiness/summary.scala.html
  app/views/estateagentbusiness/what_you_need.scala.html
  conf/bankDetails.routes
  conf/businessActivities.routes
  conf/businessDetails.routes
  conf/businessMatching.routes
  conf/messages
  release_notes/AMLS-4926.txt
  test/controllers/businessactivities/ExpectedAMLSTurnoverControllerSpec.scala
  test/views/businessactivities/involved_in_other_nameSpec.scala
  test/views/renewal/summarySpec.scala
Labels: passed QA

#1042 Amls 4997 - Bug fix for validation in renewal flow
  app/models/moneyservicebusiness/SendTheLargestAmountsOfMoney.scala
  app/models/renewal/SendTheLargestAmountsOfMoney.scala
  app/services/LandingService.scala
  app/views/renewal/send_largest_amounts_of_money.scala.html
  app/views/renewal/summary.scala.html
  release_notes/AMLS-4997.txt
  test/controllers/StatusControllerSpec.scala
  test/controllers/renewal/CustomersOutsideUKControllerSpec.scala
  test/controllers/renewal/SendTheLargestAmountsOfMoneyControllerSpec.scala
  test/controllers/renewal/SummaryControllerSpec.scala
  test/models/moneyservicebusiness/SendTheLargestAmountsOfMoneySpec.scala
  test/models/renewal/ConversionsSpec.scala
  test/models/renewal/SendTheLargestAmountsOfMoneySpec.scala
  test/services/LandingServiceSpec.scala
  test/services/RenewalServiceSpec.scala
  test/services/SubmissionServiceSpec.scala
  test/views/renewal/send_largest_amounts_of_moneySpec.scala
  test/views/renewal/summarySpec.scala
Labels: passed QA

#1045 Release note after deploy 4.375.0
  release_notes/AMLS-4838.txt
  release_notes/AMLS-4915.txt
  release_notes/AMLS-4921.txt
  release_notes/AMLS-4926.txt
  release_notes/AMLS-4927.txt
  release_notes/AMLS-4957.txt
  release_notes/AMLS-4989.txt
  release_notes/AMLS-4991.txt
  release_notes/AMLS-4997.txt
  release_notes/releases/v4.375.0/v4.375.0-16-05-2019.txt
Labels: pending review

#1041 AMLS-4988
  app/controllers/BacsConfirmationController.scala
  app/controllers/ConfirmationController.scala
  app/controllers/PaymentConfirmationController.scala
  app/controllers/RetryPaymentController.scala
  app/controllers/payments/WaysToPayController.scala
  app/controllers/renewal/AMLSTurnoverController.scala
  app/filters/ConfirmationFilter.scala
  app/models/businessmatching/BusinessMatching.scala
  app/views/confirmation/confirmation.scala.html
  app/views/confirmation/confirmation_bacs.scala.html
  app/views/confirmation/confirmation_bacs_transitional_renewal.scala.html
  app/views/confirmation/payment_failure.scala.html
  app/views/declaration/add_person.scala.html
  app/views/declaration/register_responsible_person.scala.html
  app/views/payments/bank_details.scala.html
  app/views/renewal/amls_turnover.scala.html
  app/views/renewal/involved_in_other.scala.html
  app/views/renewal/percentage.scala.html
  app/views/renewal/receiving.scala.html
  app/views/renewal/send_largest_amounts_of_money.scala.html
  app/views/renewal/which_currencies.scala.html
  conf/app.routes
  conf/messages
  conf/renewal.routes
  release_notes/AMLS-4988.txt
  test/controllers/BacsConfirmationControllerSpec.scala
  test/controllers/ConfirmationControllerSpec.scala
  test/controllers/PaymentConfirmationControllerSpec.scala
  test/controllers/RetryPaymentControllerSpec.scala
  test/controllers/payments/WaysToPayControllerSpec.scala
  test/controllers/renewal/AMLSTurnoverControllerSpec.scala
  test/models/ReturnNameValuePairSpec.scala
  test/views/confirmation/BacsConfirmationTransitionalRenewalViewSpec.scala
  test/views/confirmation/BacsConfirmationViewSpec.scala
  test/views/declaration/register_responsible_personSpec.scala
  test/views/renewal/involved_in_otherSpec.scala
Labels: passed QA

#1047 Fix rp declerartion h1
  conf/messages
Labels: pending review

#1043 Amls 4987 - Supervision/TCSP/HVD content changes
  app/views/hvd/cash_payment.scala.html
  app/views/hvd/cash_payment_text.scala.html
  app/views/hvd/expect_to_receive.scala.html
  app/views/hvd/linked_cash_payments.scala.html
  app/views/hvd/percentage.scala.html
  app/views/hvd/receiving.scala.html
  app/views/renewal/receiving.scala.html
  app/views/supervision/penalised_by_professional.scala.html
  app/views/supervision/supervision_end_reasons.scala.html
  app/views/supervision/which_professional_body.scala.html
  app/views/tcsp/what_you_need.scala.html
  conf/messages
  conf/supervision.routes
  conf/tcsp.routes
Labels: passed QA

#1052 AMLs-4943 | AMLS-4943-fix-to-merge | fixing the reverts that a merge …
  conf/messages
Labels: pending QA

#1053 Revert "Amls 4957"
  app/controllers/RegistrationProgressController.scala
  test/controllers/RegistrationProgressControllerSpec.scala
Labels: pending review

#1044 Amls 4943 - Improve error messages for Payments flow
  app/controllers/declaration/AddPersonController.scala
  app/controllers/declaration/WhoIsRegisteringController.scala
  app/models/FormTypes.scala
  app/models/businessmatching/BusinessType.scala
  app/models/declaration/AddPerson.scala
  app/models/declaration/RoleWithinBusinessRelease7.scala
  conf/messages
  release_notes/AMLS-4943.txt
  test/controllers/declaration/AddPersonControllerSpec.scala
  test/controllers/declaration/WhoIsRegisteringControllerSpec.scala
  test/models/declaration/AddPersonSpec.scala
  test/models/declaration/release7/RoleWithinBusinessRelease7Spec.scala
Labels: passed QA

#1056 Amls 4909 - ASP accessability changes
  app/views/asp/other_business_tax_matters.scala.html
  app/views/asp/services_of_business.scala.html
  app/views/tcsp/another_tcsp_supervision.scala.html
  release_notes/AMLS-4909.txt
Labels: passed QA

#1060 AMLS-4914
  app/views/businessdetails/activity_start_date.scala.html
  app/views/businessdetails/contacting_you_phone.scala.html
  app/views/businessdetails/letters_address.scala.html
  app/views/businessdetails/previously_registered.scala.html
  app/views/businessdetails/vat_registered.scala.html
  release_notes/AMLS-4914.txt
Labels: passed QA

#1059 Amls 4911 - TCSP accessibility changes
  app/views/tcsp/another_tcsp_supervision.scala.html
  app/views/tcsp/complex_corp_structure_creation.scala.html
  app/views/tcsp/only_off_the_shelf_comps_sold.scala.html
  app/views/tcsp/provided_services.scala.html
  app/views/tcsp/service_provider_types.scala.html
  app/views/tcsp/services_of_another_tcsp.scala.html
  release_notes/AMLS-4911.txt
Labels: passed QA

#1064 AMLS-5018: Minor fixes from review session
  app/views/include/forms2/IBANNumber.scala.html
  app/views/include/forms2/accountNumber.scala.html
  app/views/include/forms2/addRemove.scala.html
  app/views/include/forms2/checkYourAnswersBanks.scala.html
  app/views/include/forms2/country.scala.html
  app/views/include/forms2/fieldsetWithErrorGroup.scala.html
  app/views/include/forms2/inlineRadioGroup.scala.html
  app/views/include/forms2/input.scala.html
  app/views/include/forms2/labelWithInput.scala.html
  app/views/include/forms2/legend.scala.html
  app/views/include/forms2/radioGroup.scala.html
  app/views/include/forms2/rpInput.scala.html
  app/views/include/info_for_consideration.scala.html
  app/views/include/info_for_decision.scala.html
  public/amls.css
Labels: passed QA

#1069 Amls 5033: Dev content tidy up 'Pre-app' 'Business activities' 'Renewal'
  app/views/businessactivities/involved_in_other_name.scala.html
  app/views/businessmatching/company_registration_number.scala.html
  conf/messages
  release_notes/AMLS-5033.txt
Labels: pending QA

#1055 Amls 4999 - Add back button to change officer flow.
  app/views/changeofficer/remove_responsible_person.scala.html
  app/views/changeofficer/role_in_business.scala.html
  app/views/changeofficer/still_employed.scala.html
  release_notes/AMLS-4999.txt
  test/views/changeofficer/new_nominated_officerSpec.scala
  test/views/changeofficer/remove_responsible_personSpec.scala
  test/views/changeofficer/role_in_businessSpec.scala
  test/views/changeofficer/still_employedSpec.scala
Labels: pending QA, pending review

#1061 Amls 4913 - Submission flow accessibility
  app/views/declaration/register_partners.scala.html
  app/views/declaration/select_business_nominated_officer.scala.html
  app/views/declaration/who_is_registering_common.scala.html
  app/views/declaration/who_is_registering_this_registration.scala.html
  app/views/declaration/who_is_registering_this_renewal.scala.html
  app/views/declaration/who_is_registering_this_update.scala.html
  app/views/payments/type_of_bank.scala.html
  app/views/payments/ways_to_pay.scala.html
  release_notes/AMLS-4913.txt
Labels: passed QA
