Repository hmrc/amls-frontend, pull requests merged in 2019-02, with the labels that each got.

#910 Amls 4545
  app/views/msb/branches_or_agents.scala.html
  app/views/msb/business_use_an_ipsp.scala.html
  app/views/msb/ce_transaction_in_next_12_months.scala.html
  app/views/msb/expected_throughput.scala.html
  app/views/msb/funds_transfer.scala.html
  app/views/msb/fx_transaction_in_next_12_months.scala.html
  app/views/msb/identify_linked_transactions.scala.html
  app/views/msb/most_transactions.scala.html
  app/views/msb/send_largest_amounts_of_money.scala.html
  app/views/msb/send_money_to_other_country.scala.html
  app/views/msb/transactions_in_next_12_months.scala.html
  app/views/msb/what_you_need.scala.html
  app/views/msb/which_currencies.scala.html
  test/views/msb/branches_or_agentsSpec.scala
  test/views/msb/business_use_an_ipspSpec.scala
  test/views/msb/ce_transaction_in_next_12_monthsSpec.scala
  test/views/msb/expected_throughputSpec.scala
  test/views/msb/funds_transferSpec.scala
  test/views/msb/fx_transaction_in_next_12_monthsSpec.scala
  test/views/msb/identify_linked_transactionsSpec.scala
  test/views/msb/most_transactionsSpec.scala
  test/views/msb/send_largest_amounts_of_moneySpec.scala
  test/views/msb/send_money_to_other_countrySpec.scala
  test/views/msb/transactions_in_next_12_monthsSpec.scala
  test/views/msb/what_you_needSpec.scala
  test/views/msb/which_currenciesSpec.scala
Labels: pending QA, pending review

#914 AMLS-4676 | Added missing back link to 'How much net profit page' in renewal flow and updated unit tests
  app/views/renewal/business_turnover.scala.html
  test/views/renewal/business_turnoverSpec.scala
Labels: build passing, pending QA, pending review

#915 Amls 4142
  app/controllers/aboutthebusiness/ActivityStartDateController.scala
  app/controllers/businessactivities/RiskAssessmentController.scala
  app/controllers/tradingpremises/IsResidentialController.scala
  app/utils/ControllerHelper.scala
  app/utils/RepeatingSection.scala
  test/controllers/businessactivities/RiskAssessmentControllerSpec.scala
Labels: pending QA, pending review

#916 Amls 4640 - Trading Premises Controller DI conversion.
  app/controllers/tradingpremises/MSBServicesController.scala
  app/controllers/tradingpremises/RemoveAgentPremisesReasonsController.scala
  app/controllers/tradingpremises/RemoveTradingPremisesController.scala
  app/controllers/tradingpremises/WhatDoesYourBusinessDoController.scala
  app/controllers/tradingpremises/WhereAreTradingPremisesController.scala
  conf/tradingPremises.routes
  test/controllers/tradingpremises/MSBServicesControllerSpec.scala
  test/controllers/tradingpremises/RemoveAgentPremisesReasonsControllerSpec.scala
  test/controllers/tradingpremises/RemoveTradingPremisesControllerSpec.scala
  test/controllers/tradingpremises/WhatDoesYourBusinessDoControllerSpec.scala
  test/controllers/tradingpremises/WhereAreTradingPremisesControllerSpec.scala
Labels: build passing, reviewed

#913 Amls 3554 - Notification back buttons
  app/views/notifications/v1m0/message_details.scala.html
  app/views/notifications/v1m0/minded_to_reject.scala.html
  app/views/notifications/v1m0/minded_to_revoke.scala.html
  app/views/notifications/v1m0/no_longer_minded_to_reject.scala.html
  app/views/notifications/v1m0/no_longer_minded_to_revoke.scala.html
  app/views/notifications/v1m0/rejection_reasons.scala.html
  app/views/notifications/v1m0/revocation_reasons.scala.html
  app/views/notifications/v2m0/message_details.scala.html
  app/views/notifications/v2m0/minded_to_reject.scala.html
  app/views/notifications/v2m0/minded_to_revoke.scala.html
  app/views/notifications/v2m0/no_longer_minded_to_reject.scala.html
  app/views/notifications/v2m0/no_longer_minded_to_revoke.scala.html
  app/views/notifications/v2m0/rejection_reasons.scala.html
  app/views/notifications/v2m0/revocation_reasons.scala.html
  app/views/notifications/your_messages.scala.html
  conf/notifications/v1m0/views.txt
  conf/notifications/v2m0/views.txt
  test/views/notifications/v1m0/minded_to_rejectSpec.scala
  test/views/notifications/v1m0/minded_to_revokeSpec.scala
  test/views/notifications/v1m0/no_longer_minded_to_rejectSpec.scala
  test/views/notifications/v1m0/no_longer_minded_to_revokeSpec.scala
  test/views/notifications/v1m0/rejection_reasonsSpec.scala
  test/views/notifications/v1m0/revocation_reasonsSpec.scala
  test/views/notifications/v2m0/minded_to_rejectSpec.scala
  test/views/notifications/v2m0/minded_to_revokeSpec.scala
  test/views/notifications/v2m0/no_longer_minded_to_rejectSpec.scala
  test/views/notifications/v2m0/no_longer_minded_to_revokeSpec.scala
  test/views/notifications/v2m0/rejection_reasonsSpec.scala
  test/views/notifications/v2m0/revocation_reasonsSpec.scala
  test/views/notifications/your_messagesSpec.scala
Labels: build passing, reviewed

#917 AMLS-4678 | Changed the date of change redirect field
  app/controllers/tradingpremises/AgentNameController.scala
  test/controllers/tradingpremises/AgentNameControllerSpec.scala
Labels: build passing, reviewed

#918 AMLS-4643 | Updated EAB controllers, specs and routes with DI
  app/controllers/estateagentbusiness/PenalisedByProfessionalController.scala
  app/controllers/estateagentbusiness/PenalisedUnderEstateAgentsActController.scala
  app/controllers/estateagentbusiness/ResidentialRedressSchemeController.scala
  app/controllers/estateagentbusiness/ServicesDateOfChangeController.scala
  app/controllers/estateagentbusiness/WhatYouNeedController.scala
  conf/estateAgents.routes
  test/controllers/estateagentbusiness/PenalisedByProfessionalControllerSpec.scala
  test/controllers/estateagentbusiness/PenalisedUnderEstateAgentsActControllerSpec.scala
  test/controllers/estateagentbusiness/ResidentialRedressSchemeControllerSpec.scala
  test/controllers/estateagentbusiness/ServicesDateOfChangeControllerSpec.scala
  test/controllers/estateagentbusiness/WhatYouNeedControllerSpec.scala
Labels: pending review

#919 Amls 4636 - AbouttheBusinessControllers DI conversion
  app/connectors/BusinessMatchingConnector.scala
  app/controllers/aboutthebusiness/ActivityStartDateController.scala
  app/controllers/aboutthebusiness/ConfirmRegisteredOfficeController.scala
  app/controllers/aboutthebusiness/ContactingYouController.scala
  app/controllers/aboutthebusiness/ContactingYouPhoneController.scala
  app/controllers/aboutthebusiness/CorporationTaxRegisteredController.scala
  app/controllers/aboutthebusiness/CorrespondenceAddressController.scala
  app/controllers/aboutthebusiness/LettersAddressController.scala
  app/controllers/aboutthebusiness/PreviouslyRegisteredController.scala
  app/controllers/aboutthebusiness/RegisteredOfficeController.scala
  app/controllers/aboutthebusiness/RegisteredOfficeDateOfChangeController.scala
  app/controllers/aboutthebusiness/SummaryController.scala
  app/controllers/aboutthebusiness/VATRegisteredController.scala
  app/controllers/aboutthebusiness/WhatYouNeedController.scala
  app/services/LandingService.scala
  conf/aboutTheBusiness.routes
  test/connectors/BusinessMatchingConnectorSpec.scala
  test/controllers/aboutthebusiness/ActivityStartDateControllerSpec.scala
  test/controllers/aboutthebusiness/ConfirmRegisteredOfficeControllerSpec.scala
  test/controllers/aboutthebusiness/ContactingYouControllerSpec.scala
  test/controllers/aboutthebusiness/ContactingYouPhoneControllerSpec.scala
  test/controllers/aboutthebusiness/CorporationTaxRegisteredControllerSpec.scala
  test/controllers/aboutthebusiness/CorrespondenceAddressControllerSpec.scala
  test/controllers/aboutthebusiness/LettersAddressControllerSpec.scala
  test/controllers/aboutthebusiness/PreviouslyRegisteredControllerSpec.scala
  test/controllers/aboutthebusiness/RegisteredOfficeControllerSpec.scala
  test/controllers/aboutthebusiness/RegisteredOfficeDateOfChangeControllerSpec.scala
  test/controllers/aboutthebusiness/SummaryControllerSpec.scala
  test/controllers/aboutthebusiness/VATRegisteredControllerSpec.scala
  test/controllers/aboutthebusiness/WhatYouNeedControllerSpec.scala
Labels: build passing, reviewed

#920 Amls 4267
  app/controllers/changeofficer/FurtherUpdatesController.scala
  test/controllers/changeofficer/FurtherUpdatesControllerSpec.scala
Labels: pending review

#921 Amls 4682 - Payment flow back button
  app/views/payments/bank_details.scala.html
  app/views/payments/type_of_bank.scala.html
  app/views/payments/ways_to_pay.scala.html
  test/views/payments/bank_detailsSpec.scala
  test/views/payments/type_of_bankSpec.scala
  test/views/payments/ways_to_paySpec.scala
Labels: build passing, pending QA, pending review

#922 AMLS 4679 | Country auto complete fields
  app/controllers/aboutthebusiness/RegisteredOfficeController.scala
  app/controllers/renewal/CustomersOutsideUKController.scala
  app/controllers/renewal/SendTheLargestAmountsOfMoneyController.scala
  app/views/aboutthebusiness/registered_office.scala.html
  app/views/renewal/customers_outside_uk.scala.html
  app/views/renewal/send_largest_amounts_of_money.scala.html
  public/amls.js
  public/autocomplete/location-autocomplete-graph.json
  test/controllers/aboutthebusiness/RegisteredOfficeControllerSpec.scala
  test/controllers/renewal/SendTheLargestAmountsOfMoneyControllerSpec.scala
  test/services/ProgressServiceSpec.scala
  test/views/aboutthebusiness/registered_officeSpec.scala
  test/views/renewal/customers_outside_ukSpec.scala
  test/views/renewal/send_largest_amounts_of_moneySpec.scala
Labels: pending QA, pending review

#923 AMLS-4675 | Buf fix for notifications with <no subject> and no content. Missing content was defaulted to 'no content' text when no message details are available.
  app/services/NotificationService.scala
  conf/messages
  test/services/NotificationServiceSpec.scala
Labels: build passing, pending QA, pending review

#926 AMLS-4675 | Further bug fix for NoSubject notifications
  app/models/notifications/NotificationDetails.scala
  app/models/notifications/NotificationRow.scala
  app/services/NotificationService.scala
  app/utils/ContactTypeHelper.scala
  app/views/notifications/your_messages.scala.html
  conf/messages
  test/models/notifications/NotificationDetailsSpec.scala
  test/models/notifications/NotificationRowSpec.scala
  test/utils/ContactTypeHelperSpec.scala
Labels: build passing, pending QA, reviewed

#924 AMLS 4635 | Updated DI in business matching
  app/controllers/businessmatching/BusinessTypeController.scala
  app/controllers/businessmatching/TypeOfBusinessController.scala
  conf/businessMatching.routes
  test/controllers/businessmatching/BusinessTypeControllerSpec.scala
  test/controllers/businessmatching/TypeOfBusinessControllerSpec.scala
Labels: pending QA, pending review

#927 Amls 4695 - Declaration Controllers DI
  app/controllers/declaration/AddPersonController.scala
  app/controllers/declaration/DeclarationController.scala
  app/controllers/declaration/WhoIsRegisteringController.scala
  conf/app.routes
  test/controllers/declaration/AddPersonControllerSpec.scala
  test/controllers/declaration/DeclarationControllerSpec.scala
  test/controllers/declaration/WhoIsRegisteringControllerSpec.scala
Labels: build passing, pending QA, pending review

#933 Added release note generation scripts and first release note
  .github/PULL_REQUEST_TEMPLATE.md
  generate-my-release-note.sh
  generate-release-notes.sh
  release_notes/AMLS-4697.txt
Labels: pending QA, pending review

#930 AMLS-3976 | Added "HVD" to "What you need" title
  app/views/hvd/what_you_need.scala.html
Labels: pending QA, pending review

#936 Fix build WhatYouNeedController
  test/controllers/hvd/WhatYouNeedControllerSpec.scala
Labels: pending review

#932 Amls 4460 - Apply/Remove Gutters from Service
  app/views/businessactivities/expected_amls_turnover.scala.html
  app/views/businessactivities/involved_in_other_name.scala.html
  app/views/businessmatching/updateservice/remove/need_more_information.scala.html
  app/views/estateagentbusiness/penalised_by_professional.scala.html
  app/views/estateagentbusiness/penalised_under_estate_agents_act.scala.html
  app/views/hvd/products.scala.html
  app/views/include/current_business_types.scala.html
  app/views/include/registered_office_helper.scala.html
  app/views/responsiblepeople/experience_training.scala.html
  app/views/responsiblepeople/legal_name.scala.html
  app/views/responsiblepeople/nationality.scala.html
  app/views/supervision/which_professional_body.scala.html
  release_notes/AMLS-4460.txt
Labels: build passing, passed QA, reviewed

#937 AMLS-4669 | Content Changes for BankDetails
  conf/messages
  release_notes/AMLS-4669.txt
Labels: Do-Not-Merge, build passing, pending QA, reviewed

#934 Amls 4856 - Correct the content and contractions About the business
  app/models/FormTypes.scala
  app/views/aboutthebusiness/activity_start_date.scala.html
  app/views/aboutthebusiness/contacting_you.scala.html
  app/views/aboutthebusiness/contacting_you_phone.scala.html
  app/views/aboutthebusiness/correspondence_address.scala.html
  app/views/aboutthebusiness/registered_office.scala.html
  conf/messages
  release_notes/AMLS-4856.txt
  test/models/aboutthebusiness/ContactingYouEmailSpec.scala
Labels: Do-Not-Merge, build passing, pending QA, reviewed

#938 Amls 4156 - Edit button on CYA for msb
  app/controllers/msb/SendMoneyToOtherCountryController.scala
  app/controllers/msb/SendTheLargestAmountsOfMoneyController.scala
  app/views/msb/summary.scala.html
  release_notes/AMLS-4156.txt
  test/controllers/msb/SummaryControllerSpec.scala
Labels: build passing, passed QA, reviewed

#935 AMLS-4127 | Changed Business Activities to Responsible People
  app/views/declaration/register_responsible_person.scala.html
Labels: pending QA, pending review

#941 AMLS-4156 | Amended matching on edit field
  app/controllers/msb/SendMoneyToOtherCountryController.scala
Labels: build passing, passed QA

#945 Generate release notes for v4.246.0
  release_notes/AMLS-4127.txt
  release_notes/AMLS-4156.txt
  release_notes/AMLS-4354.txt
  release_notes/AMLS-4460.txt
  release_notes/AMLS-4669.txt
  release_notes/AMLS-4697.txt
  release_notes/AMLS-4702.txt
  release_notes/AMLS-4703.txt
  release_notes/AMLS-4856.txt
  release_notes/releases/v4.246.0/v4.246.0-21-02-2019.txt
Labels: pending review

#946 AMLS-4381 | Removed "Are they nominated officer?" after creation of a responsible person
  app/controllers/responsiblepeople/AreTheyNominatedOfficerController.scala
  app/controllers/responsiblepeople/PositionWithinBusinessController.scala
  app/views/responsiblepeople/are_they_nominated_officer.scala.html
  conf/responsiblePeople.routes
  release_notes/AMLS-4381.txt
  test/controllers/responsiblepeople/AreTheyNominatedOfficerControllerSpec.scala
  test/controllers/responsiblepeople/PositionWithinBusinessControllerSpec.scala
  test/views/responsiblepeople/are_they_nominated_officerSpec.scala
Labels: pending QA

#943 Amls 4344 - Default Fee Rate Values
  app/config/ApplicationConfig.scala
  app/typeclasses/confirmation/FeeCalculations.scala
  app/utils/FeeRateHelper.scala
  conf/application.conf
  release_notes/AMLS-4344.txt
  test/generators/ResponsiblePersonGenerator.scala
  test/services/ConfirmationServiceSpec.scala
  test/services/ConfirmationServiceSpecWithPhase2Changes.scala
  test/typeclasses/confirmation/ResponsiblePeopleRowsPhase2Spec.scala
  test/utils/FeeRateHelperSpec.scala
Labels: passed QA

#949 Amls 4734
  app/views/declaration/select_business_nominated_officer.scala.html
  release_notes/AMLS-4734.txt
Labels: pending QA

#947 AMLS-3717 | New Officer Controller validation
  app/controllers/changeofficer/NewOfficerController.scala
  release_notes/AMLS-3717.txt
  test/controllers/changeofficer/NewOfficerControllerSpec.scala
  test/generators/ResponsiblePersonGenerator.scala
  test/models/responsiblepeople/ResponsiblePersonSpec.scala
Labels: passed QA

#948 Business activities - Does your business do anything else failing val…
  app/models/businessactivities/BusinessActivities.scala
  release_notes/AMLS-4748.txt
  test/models/businessactivities/BusinessActivitiesSpec.scala
Labels: passed QA, reviewed

#951 Amls 4728 - Updated YTP "continue" button content
  app/views/tradingpremises/your_trading_premises.scala.html
  release_notes/AMLS-4728.txt
  test/views/tradingpremises/your_trading_premisesSpec.scala
Labels: build passing

#955 Generated release notes for v4.257.0
  release_notes/AMLS-3717.txt
  release_notes/AMLS-4344.txt
  release_notes/AMLS-4381.txt
  release_notes/AMLS-4727.txt
  release_notes/AMLS-4728.txt
  release_notes/AMLS-4734.txt
  release_notes/AMLS-4748.txt
  release_notes/releases/v4.257.0/v4.257.0-28-02-2019.txt
Labels: pending review
