Repository hmrc/amls-frontend, pull requests merged in 2019-08, with the labels that each got.

#1148 AMLS-5081 Change Officer: Moving to the new Auth Client FE
  app/connectors/cache/DataCacheConnector.scala
  app/controllers/changeofficer/Helpers.scala
  app/controllers/changeofficer/NewOfficerController.scala
  app/controllers/changeofficer/RemoveResponsiblePersonController.scala
  app/controllers/changeofficer/RoleInBusinessController.scala
  app/controllers/changeofficer/StillEmployedController.scala
  app/utils/RepeatingSection.scala
  release_notes/AMLS-5081.txt
  test/controllers/changeofficer/NewOfficerControllerSpec.scala
  test/controllers/changeofficer/RemoveResponsiblePersonControllerSpec.scala
  test/controllers/changeofficer/RoleInBusinessControllerSpec.scala
  test/controllers/changeofficer/StillEmployedControllerSpec.scala
Labels: pending QA

#1142 Amls 5086 - MSB Auth implementation
  app/controllers/msb/BranchesOrAgentsController.scala
  app/controllers/msb/BranchesOrAgentsWhichCountriesController.scala
  app/controllers/msb/BusinessUseAnIPSPController.scala
  app/controllers/msb/CETransactionsInNext12MonthsController.scala
  app/controllers/msb/ExpectedThroughputController.scala
  app/controllers/msb/FXTransactionsInNext12MonthsController.scala
  app/controllers/msb/FundsTransferController.scala
  app/controllers/msb/IdentifyLinkedTransactionsController.scala
  app/controllers/msb/MoneySourcesController.scala
  app/controllers/msb/MostTransactionsController.scala
  app/controllers/msb/SendMoneyToOtherCountryController.scala
  app/controllers/msb/SendTheLargestAmountsOfMoneyController.scala
  app/controllers/msb/SummaryController.scala
  app/controllers/msb/TransactionsInNext12MonthsController.scala
  app/controllers/msb/UsesForeignCurrenciesController.scala
  app/controllers/msb/WhatYouNeedController.scala
  app/controllers/msb/WhichCurrenciesController.scala
  release_notes/AMLS-5086.txt
  test/controllers/msb/BranchesOrAgentsHasCountriesControllerSpec.scala
  test/controllers/msb/BranchesOrAgentsWhichCountriesControllerSpec.scala
  test/controllers/msb/BusinessUseAnIPSPControllerSpec.scala
  test/controllers/msb/CETransactionsInNext12MonthsControllerSpec.scala
  test/controllers/msb/ExpectedThroughputControllerSpec.scala
  test/controllers/msb/FXTransactionsInNext12MonthsControllerSpec.scala
  test/controllers/msb/FundsTransferControllerSpec.scala
  test/controllers/msb/IdentifyLinkedTransactionsControllerSpec.scala
  test/controllers/msb/MoneySourcesControllerSpec.scala
  test/controllers/msb/MostTransactionsControllerSpec.scala
  test/controllers/msb/SendMoneyToOtherCountryControllerSpec.scala
  test/controllers/msb/SendTheLargestAmountsOfMoneyControllerSpec.scala
  test/controllers/msb/SummaryControllerSpec.scala
  test/controllers/msb/TransactionsInNext12MonthsControllerSpec.scala
  test/controllers/msb/UsesForeignCurrenciesControllerSpec.scala
  test/controllers/msb/WhatYouNeedControllerSpec.scala
  test/controllers/msb/WhichCurrenciesControllerSpec.scala
  test/controllers/tradingpremises/BusinessStructureControllerRelease7Spec.scala
Labels: pending QA

#1143 Amls 5093 - TCSP - Moving to the new Auth Client FE
  app/controllers/tcsp/AnotherTCSPSupervisionController.scala
  app/controllers/tcsp/ComplexCorpStructureCreationController.scala
  app/controllers/tcsp/OnlyOffTheShelfCompsSoldController.scala
  app/controllers/tcsp/ProvidedServicesController.scala
  app/controllers/tcsp/ServicesOfAnotherTCSPController.scala
  app/controllers/tcsp/SummaryController.scala
  app/controllers/tcsp/TcspTypesController.scala
  app/controllers/tcsp/WhatYouNeedController.scala
  release_notes/AMLS-5093.txt
  test/controllers/tcsp/AnotherTCSPSupervisionControllerSpec.scala
  test/controllers/tcsp/ComplexCorpStructureCreationControllerSpec.scala
  test/controllers/tcsp/OnlyOffTheShelfCompsSoldControllerSpec.scala
  test/controllers/tcsp/ProvidedServicesControllerSpec.scala
  test/controllers/tcsp/ServicesOfAnotherTCSPControllerSpec.scala
  test/controllers/tcsp/SummaryControllerSpec.scala
  test/controllers/tcsp/TcspTypesControllerSpec.scala
  test/controllers/tcsp/WhatYouNeedControllerSpec.scala
Labels: pending QA

#1152 Amls 5092 - Supervision - Moving to the new Auth Client FE
  app/controllers/supervision/AnotherBodyController.scala
  app/controllers/supervision/PenalisedByProfessionalController.scala
  app/controllers/supervision/ProfessionalBodyMemberController.scala
  app/controllers/supervision/SummaryController.scala
  app/controllers/supervision/SupervisionEndController.scala
  app/controllers/supervision/SupervisionEndReasonsController.scala
  app/controllers/supervision/SupervisionStartController.scala
  app/controllers/supervision/WhatYouNeedController.scala
  app/controllers/supervision/WhichProfessionalBodyController.scala
  release_notes/AMLS-5092.txt
  test/controllers/supervision/AnotherBodyControllerSpec.scala
  test/controllers/supervision/PenalisedByProfessionalControllerSpec.scala
  test/controllers/supervision/ProfessionalBodyMemberControllerSpec.scala
  test/controllers/supervision/SummaryControllerSpec.scala
  test/controllers/supervision/SupervisionEndControllerSpec.scala
  test/controllers/supervision/SupervisionEndReasonsControllerSpec.scala
  test/controllers/supervision/SupervisionStartControllerSpec.scala
  test/controllers/supervision/WhatYouNeedControllerSpec.scala
  test/controllers/supervision/WhichProfessionalBodyControllerSpec.scala
Labels: pending QA

#1149 Added ID to 45 days paragraph for optimizely selector
  app/views/include/status/rightpanel_submissionreadyforreview.scala.html
  release_notes/AMLS-5199.txt
Labels: pending QA, pending review

#1155 Update auth wip master 2
  app/views/include/status/rightpanel_submissionreadyforreview.scala.html
  release_notes/AMLS-5199.txt
Labels: pending review

#1153 Amls 5071 - Remove ARIA role of tooltip from error summary list items
  app/views/include/forms2/errorSummary.scala.html
  release_notes/AMLS-5071.txt
Labels: passed QA

#1157 AMLS-5094 | Trading Premises
  app/connectors/AmlsConnector.scala
  app/controllers/tradingpremises/ActivityStartDateController.scala
  app/controllers/tradingpremises/AgentCompanyDetailsController.scala
  app/controllers/tradingpremises/AgentCompanyNameController.scala
  app/controllers/tradingpremises/AgentNameController.scala
  app/controllers/tradingpremises/AgentPartnershipController.scala
  app/controllers/tradingpremises/BusinessStructureController.scala
  app/controllers/tradingpremises/ConfirmAddressController.scala
  app/controllers/tradingpremises/DetailedAnswersController.scala
  app/controllers/tradingpremises/IsResidentialController.scala
  app/controllers/tradingpremises/MSBServicesController.scala
  app/controllers/tradingpremises/RegisteringAgentPremisesController.scala
  app/controllers/tradingpremises/RemoveAgentPremisesReasonsController.scala
  app/controllers/tradingpremises/RemoveTradingPremisesController.scala
  app/controllers/tradingpremises/TradingPremisesAddController.scala
  app/controllers/tradingpremises/WhatDoesYourBusinessDoController.scala
  app/controllers/tradingpremises/WhatYouNeedController.scala
  app/controllers/tradingpremises/WhereAreTradingPremisesController.scala
  app/controllers/tradingpremises/YourTradingPremisesController.scala
  app/services/StatusService.scala
  app/utils/BusinessName.scala
  app/utils/RepeatingSection.scala
  release_notes/AMLS-5094.txt
  test/controllers/businessdetails/CorrespondenceAddressIsUkControllerSpec.scala
  test/controllers/tradingpremises/ActivityStartDateControllerSpec.scala
  test/controllers/tradingpremises/AgentCompanyDetailsControllerSpec.scala
  test/controllers/tradingpremises/AgentCompanyNameControllerSpec.scala
  test/controllers/tradingpremises/AgentNameControllerSpec.scala
  test/controllers/tradingpremises/AgentPartnershipControllerSpec.scala
  test/controllers/tradingpremises/BusinessStructureControllerSpec.scala
  test/controllers/tradingpremises/ConfirmAddressControllerSpec.scala
  test/controllers/tradingpremises/DetailedAnswersControllerSpec.scala
  test/controllers/tradingpremises/IsResidentialControllerSpec.scala
  test/controllers/tradingpremises/MSBServicesControllerSpec.scala
  test/controllers/tradingpremises/RegisteringAgentPremisesControllerSpec.scala
  test/controllers/tradingpremises/RemoveAgentPremisesReasonsControllerSpec.scala
  test/controllers/tradingpremises/RemoveTradingPremisesControllerSpec.scala
  test/controllers/tradingpremises/TradingPremisesAddControllerSpec.scala
  test/controllers/tradingpremises/WhatDoesYourBusinessDoControllerSpec.scala
  test/controllers/tradingpremises/WhatYouNeedControllerSpec.scala
  test/controllers/tradingpremises/WhereAreTradingPremisesControllerSpec.scala
  test/controllers/tradingpremises/YourTradingPremisesControllerSpec.scala
Labels: pending QA

#1154 Amls 5207 - Implementation of Visually Hidden Error content on all the Countries in the service
  app/views/include/forms2/country_autocomplete.scala.html
  app/views/include/forms2/currency.scala.html
  release_notes/AMLS-5207.txt
Labels: passed QA

#1159 AMLS-5231 | Updated content on payment screen
  conf/messages
  release_notes/AMLS-5231.txt
Labels: passed QA

#1160 Amls 5010 - getMessage instead of toString
  app/models/asp/ServicesOfBusiness.scala
  app/models/estateagentbusiness/Service.scala
  app/models/tradingpremises/TradingPremisesMsbServices.scala
  app/views/asp/summary.scala.html
  app/views/businessmatching/summary.scala.html
  app/views/estateagentbusiness/summary.scala.html
  app/views/tradingpremises/msb_services.scala.html
  app/views/tradingpremises/summary_details.scala.html
  release_notes/AMLS-5010.txt
Labels: passed QA

#1161 Remove question is your company registered for corporatrion tax from …
  app/controllers/businessdetails/CorporationTaxRegisteredController.scala
  app/controllers/businessdetails/VATRegisteredController.scala
  app/views/businessdetails/corporation_tax_registered.scala.html
  conf/businessDetails.routes
  release_notes/AMLS-4813.txt
  test/controllers/businessdetails/CorporationTaxRegisteredControllerSpec.scala
  test/views/businessdetails/corporation_tax_registeredSpec.scala
Labels: passed QA

#1164 Fix failing build
  app/views/businessmatching/summary.scala.html
Labels: pending review

#1163 Add H1 to standard error page for tracking.
  app/views/error.scala.html
  release_notes/AMLS-5220.txt
Labels: passed QA

#1168 AMLS-5088 | Renewals Auth Update
  app/controllers/renewal/AMLSTurnoverController.scala
  app/controllers/renewal/BusinessTurnoverController.scala
  app/controllers/renewal/CETransactionsInLast12MonthsController.scala
  app/controllers/renewal/CashPaymentsCustomersNotMetController.scala
  app/controllers/renewal/CustomersOutsideIsUKController.scala
  app/controllers/renewal/CustomersOutsideUKController.scala
  app/controllers/renewal/FXTransactionsInLast12MonthsController.scala
  app/controllers/renewal/HowCashPaymentsReceivedController.scala
  app/controllers/renewal/InvolvedInOtherController.scala
  app/controllers/renewal/MoneySourcesController.scala
  app/controllers/renewal/MostTransactionsController.scala
  app/controllers/renewal/PercentageOfCashPaymentOver15000Controller.scala
  app/controllers/renewal/RenewalProgressController.scala
  app/controllers/renewal/SendMoneyToOtherCountryController.scala
  app/controllers/renewal/SendTheLargestAmountsOfMoneyController.scala
  app/controllers/renewal/SummaryController.scala
  app/controllers/renewal/TotalThroughputController.scala
  app/controllers/renewal/TransactionsInLast12MonthsController.scala
  app/controllers/renewal/UsesForeignCurrenciesController.scala
  app/controllers/renewal/WhatYouNeedController.scala
  app/controllers/renewal/WhichCurrenciesController.scala
  app/services/ProgressService.scala
  app/services/RenewalService.scala
  app/services/StatusService.scala
  release_notes/AMLS-5088.txt
  test/controllers/renewal/AMLSTurnoverControllerSpec.scala
  test/controllers/renewal/BusinessTurnoverControllerSpec.scala
  test/controllers/renewal/CETransactionsInLast12MonthsControllerSpec.scala
  test/controllers/renewal/CashPaymentsCustomersNotMetControllerSpec.scala
  test/controllers/renewal/CustomersOutsideIsUKControllerSpec.scala
  test/controllers/renewal/CustomersOutsideUKControllerSpec.scala
  test/controllers/renewal/FXTransactionsInLast12MonthsControllerSpec.scala
  test/controllers/renewal/HowCashPaymentsReceivedControllerSpec.scala
  test/controllers/renewal/InvolvedInOtherControllerSpec.scala
  test/controllers/renewal/MoneySourcesControllerSpec.scala
  test/controllers/renewal/MostTransactionsControllerSpec.scala
  test/controllers/renewal/PercentageOfCashPaymentOver15000ControllerSpec.scala
  test/controllers/renewal/RenewalProgressControllerSpec.scala
  test/controllers/renewal/SendMoneyToOtherCountryControllerSpec.scala
  test/controllers/renewal/SendTheLargestAmountsOfMoneyControllerSpec.scala
  test/controllers/renewal/SummaryControllerSpec.scala
  test/controllers/renewal/TotalThroughputControllerSpec.scala
  test/controllers/renewal/TransactionsInLast12MonthsControllerSpec.scala
  test/controllers/renewal/UsesForeignCurrenciesControllerSpec.scala
  test/controllers/renewal/WhatYouNeedControllerSpec.scala
  test/controllers/renewal/WhichCurrenciesControllerSpec.scala
Labels: pending QA

#1170 Amls 5095 - Withdrawal section auth
  app/connectors/AmlsConnector.scala
  app/controllers/withdrawal/WithdrawApplicationController.scala
  app/controllers/withdrawal/WithdrawalReasonController.scala
  release_notes/AMLS-5095.txt
  test/controllers/withdrawal/WithdrawApplicationControllerSpec.scala
  test/controllers/withdrawal/WithdrawalReasonControllerSpec.scala
Labels: pending QA, pending review

#1167 Amls 5085 - HVD - Moving to the new Auth Client FE
  app/controllers/hvd/CashPaymentController.scala
  app/controllers/hvd/CashPaymentFirstDateController.scala
  app/controllers/hvd/ExciseGoodsController.scala
  app/controllers/hvd/ExpectToReceiveCashPaymentsController.scala
  app/controllers/hvd/HowWillYouSellGoodsController.scala
  app/controllers/hvd/HvdDateOfChangeController.scala
  app/controllers/hvd/LinkedCashPaymentsController.scala
  app/controllers/hvd/PercentageOfCashPaymentOver15000Controller.scala
  app/controllers/hvd/ProductsController.scala
  app/controllers/hvd/ReceiveCashPaymentsController.scala
  app/controllers/hvd/SummaryController.scala
  app/controllers/hvd/WhatYouNeedController.scala
  release_notes/AMLS-5085.txt
  test/controllers/hvd/CashPaymentFirstDateControllerSpec.scala
  test/controllers/hvd/CashPaymentOverTenThousandEurosControllerSpec.scala
  test/controllers/hvd/ExciseGoodsControllerSpec.scala
  test/controllers/hvd/ExpectToReceiveCashPaymentsControllerSpec.scala
  test/controllers/hvd/HowWillYouSellGoodsControllerSpec.scala
  test/controllers/hvd/HvdDateOfChangeControllerSpec.scala
  test/controllers/hvd/LinkedCashPaymentsControllerSpec.scala
  test/controllers/hvd/PercentageOfCashPaymentOver15000ControllerSpec.scala
  test/controllers/hvd/ProductsControllerSpec.scala
  test/controllers/hvd/ReceiveCashPaymentsControllerSpec.scala
  test/controllers/hvd/SummaryControllerSpec.scala
  test/controllers/hvd/WhatYouNeedControllerSpec.scala
Labels: pending QA

#1171 Amls 5083 - Deregister auth implementation
  app/connectors/AmlsConnector.scala
  app/controllers/deregister/DeRegisterApplicationController.scala
  app/controllers/deregister/DeregistrationReasonController.scala
  release_notes/AMLS-5083.txt
  test/controllers/deregister/DeRegisterApplicationControllerSpec.scala
  test/controllers/deregister/DeregistrationReasonControllerSpec.scala
Labels: pending QA, pending review

#1173 Alms 5084: EAB - Moving to the new Auth Client FE
  app/controllers/estateagentbusiness/BusinessServicesController.scala
  app/controllers/estateagentbusiness/PenalisedByProfessionalController.scala
  app/controllers/estateagentbusiness/PenalisedUnderEstateAgentsActController.scala
  app/controllers/estateagentbusiness/ResidentialRedressSchemeController.scala
  app/controllers/estateagentbusiness/ServicesDateOfChangeController.scala
  app/controllers/estateagentbusiness/SummaryController.scala
  app/controllers/estateagentbusiness/WhatYouNeedController.scala
  release_notes/AMLS-5084.txt
  test/controllers/estateagentbusiness/BusinessServicesControllerSpec.scala
  test/controllers/estateagentbusiness/PenalisedByProfessionalControllerSpec.scala
  test/controllers/estateagentbusiness/PenalisedUnderEstateAgentsActControllerSpec.scala
  test/controllers/estateagentbusiness/ResidentialRedressSchemeControllerSpec.scala
  test/controllers/estateagentbusiness/ServicesDateOfChangeControllerSpec.scala
  test/controllers/estateagentbusiness/SummaryControllerSpec.scala
  test/controllers/estateagentbusiness/WhatYouNeedControllerSpec.scala
Labels: pending QA, pending review

#1178 BUG-FIX: Auth implementation correction in payments controllers
  app/connectors/AmlsConnector.scala
  app/controllers/payments/BankDetailsController.scala
  app/controllers/payments/WaysToPayController.scala
  app/services/StatusService.scala
  test/controllers/payments/WaysToPayControllerSpec.scala
Labels: pending QA

#1175 AMLS-5209 | RP address rejects spaces in mandatory fields
  app/models/FormTypes.scala
  app/models/responsiblepeople/PersonAddress.scala
  release_notes/AMLS-5209.txt
Labels: passed QA

#1176 AMLS-5246 | Fixed misplaced errors in "Which currencies..."
  app/controllers/msb/BranchesOrAgentsWhichCountriesController.scala
  app/controllers/msb/WhichCurrenciesController.scala
  app/utils/ControllerHelper.scala
  release_notes/AMLS-5246.txt
  test/utils/ControllerHelperSpec.scala
Labels: pending QA

#1177 Amls 5205 - Previous experience content changes
  app/controllers/businessactivities/ExpectedAMLSTurnoverController.scala
  app/controllers/businessactivities/InvolvedInOtherController.scala
  app/controllers/renewal/AMLSTurnoverController.scala
  app/controllers/renewal/InvolvedInOtherController.scala
  app/controllers/responsiblepeople/DetailedAnswersController.scala
  app/controllers/responsiblepeople/ExperienceTrainingController.scala
  app/models/businessmatching/BusinessMatching.scala
  app/views/responsiblepeople/detailed_answers.scala.html
  app/views/responsiblepeople/experience_training.scala.html
  conf/messages
  release_notes/AMLS-5205.txt
  test/controllers/responsiblepeople/DetailedAnswersControllerSpec.scala
  test/views/responsiblepeople/detailed_answersSpec.scala
  test/views/responsiblepeople/experience_trainingSpec.scala
Labels: passed QA
