Repository hmrc/amls-frontend, pull requests merged in 2019-06, with the labels that each got.

#1067 AMLS-4384: PPoB Non UK allows user to select United Kingdom.
  app/controllers/responsiblepeople/CountryOfBirthController.scala
  app/models/businessdetails/CorrespondenceAddress.scala
  app/models/businessdetails/RegisteredOffice.scala
  app/models/responsiblepeople/CountryOfBirth.scala
  app/models/responsiblepeople/PersonAddress.scala
  app/models/responsiblepeople/ResponsiblePersonAddress.scala
  app/models/responsiblepeople/ResponsiblePersonCurrentAddress.scala
  app/views/include/forms2/country_autocomplete.scala.html
  app/views/responsiblepeople/additional_address.scala.html
  app/views/responsiblepeople/additional_extra_address.scala.html
  app/views/responsiblepeople/country_of_birth.scala.html
  app/views/responsiblepeople/current_address.scala.html
  conf/messages
  release_notes/AMLS-4384.txt
  test/audit/AddressCreatedEventSpec.scala
  test/controllers/responsiblepeople/AdditionalAddressControllerSpec.scala
  test/controllers/responsiblepeople/CurrentAddressControllerSpec.scala
  test/models/businessdetails/CorrespondenceAddressSpec.scala
  test/models/businessdetails/RegisteredOfficeSpec.scala
  test/models/responsiblepeople/CountryOfBirthSpec.scala
  test/models/responsiblepeople/PersonAddressSpec.scala
  test/models/responsiblepeople/ResponsiblePersonAddressHistorySpec.scala
  test/services/LandingServiceSpec.scala
Labels: passed QA

#1070 Improve test coverage read status response
  test/models/ReadStatusResponseSpec.scala
Labels: pending review

#1072 Amls 4919 - Add h1 to legend for HVD flow
  app/views/hvd/cash_payment.scala.html
  app/views/hvd/cash_payment_first_date.scala.html
  app/views/hvd/excise_goods.scala.html
  app/views/hvd/expect_to_receive.scala.html
  app/views/hvd/how_will_you_sell_goods.scala.html
  app/views/hvd/linked_cash_payments.scala.html
  app/views/hvd/percentage.scala.html
  app/views/hvd/products.scala.html
  app/views/hvd/receiving.scala.html
  release_notes/AMLS-4919.txt
  test/views/hvd/productsSpec.scala
Labels: passed QA

#1079 Add google tag manager to content security policy
  conf/application.conf
  release_notes/AMLS-4580.txt
Labels: pending review

#1077 Amls 5064 - Renewal: Which currencies did you supply repeats Hint text
  app/views/msb/which_currencies.scala.html
  app/views/renewal/which_currencies.scala.html
  conf/messages
  release_notes/AMLS-5064.txt
Labels: passed QA

#1082 AMLS-5058 | Bug fix: Editing HVD Question does not lead to section being 'Updated'
  app/models/hvd/Hvd.scala
  release_notes/AMLS-5058.txt
Labels: passed QA

#1086 AMLS-5052 | Bug fix: You have submitted page VO issue
  app/views/confirmation/confirmation_bacs.scala.html
  app/views/confirmation/confirmation_bacs_transitional_renewal.scala.html
  release_notes/AMLS-5052.txt
Labels: passed QA

#1076 Amls 5019 - Rename 'Supervision' to 'Supervision details'
  conf/app.routes
  conf/messages
  release_notes/AMLS-5019.txt
Labels: passed QA

#1089 AMLS-5073 - fix to radio buttons not stacked bug
  app/views/supervision/another_body.scala.html
  app/views/supervision/penalised_by_professional.scala.html
Labels: passed QA

#1073 AMLS-4922 Accessibility for Trading Premises flow
  app/views/include/forms2/date.scala.html
  app/views/tradingpremises/activity_start_date.scala.html
  app/views/tradingpremises/agent_company_name.scala.html
  app/views/tradingpremises/agent_partnership.scala.html
  app/views/tradingpremises/business_structure.scala.html
  app/views/tradingpremises/confirm_address.scala.html
  app/views/tradingpremises/is_residential.scala.html
  app/views/tradingpremises/msb_services.scala.html
  app/views/tradingpremises/registering_agent_premises.scala.html
  app/views/tradingpremises/remove_agent_premises_reasons.scala.html
  app/views/tradingpremises/remove_trading_premises.scala.html
  app/views/tradingpremises/what_does_your_business_do.scala.html
  app/views/tradingpremises/where_are_trading_premises.scala.html
  release_notes/AMLS-4922.txt
  test/views/tradingpremises/agent_company_nameSpec.scala
  test/views/tradingpremises/agent_partnershipSpec.scala
  test/views/tradingpremises/remove_trading_premisesSpec.scala
Labels: passed QA

#1088 AMLS-4918 - Bank details accessability changes
  app/views/bankdetails/bank_account_name.scala.html
  app/views/bankdetails/bank_account_types.scala.html
  app/views/bankdetails/has_bank_account.scala.html
  release_notes/AMLS-4918.txt
  test/views/bankdetails/bank_account_nameSpec.scala
Labels: passed QA

#1093 AMLS-4884: Bulleted list on cya for document ra
  app/views/businessactivities/summary.scala.html
Labels: pending QA, pending review

#1092 AMLS-5060 | added test and code to fix jira AMLS-5060
  app/controllers/supervision/ProfessionalBodyMemberController.scala
  test/controllers/supervision/ProfessionalBodyMemberControllerSpec.scala
Labels: passed QA

#1090 Amls 5054 - CredId instead of OID for Mongo
  app/connectors/AuthConnector.scala
  app/connectors/cache/DataCacheConnector.scala
  app/connectors/cache/MongoCacheConnector.scala
  app/services/cache/MongoCacheClient.scala
  release_notes/AMLS-5054.txt
  test/connectors/AuthConnectorSpec.scala
  test/connectors/cache/DataCacheConnectorSpec.scala
  test/connectors/cache/MongoCacheConnectorSpec.scala
Labels: pending QA

#1097 Amls 5113 - Change H1 for 'Is this right address to send you letters'
  conf/messages
  release_notes/AMLS-5113.txt
Labels: passed QA

#1107 Release notes 4.434.0
  release_notes/releases/v4.434.0/v4.434.0-26-06-2019.txt
Labels: pending review

#1098 AMLS-5103
  conf/messages
  release_notes/AMLS-5103.txt
Labels: passed QA

#1100 Amls 5110 - Remove unnecessary H2 content from RP summary page
  app/views/responsiblepeople/your_responsible_people.scala.html
  release_notes/AMLS-5110.txt
Labels: passed QA

#1101 AMLS-4923: Accessibility for MSB flow
  app/views/msb/business_use_an_ipsp.scala.html
  app/views/msb/ce_transaction_in_next_12_months.scala.html
  app/views/msb/expected_throughput.scala.html
  app/views/msb/funds_transfer.scala.html
  app/views/msb/fx_transaction_in_next_12_months.scala.html
  app/views/msb/identify_linked_transactions.scala.html
  app/views/msb/money_sources.scala.html
  app/views/msb/most_transactions.scala.html
  app/views/msb/send_largest_amounts_of_money.scala.html
  app/views/msb/send_money_to_other_country.scala.html
  app/views/msb/transactions_in_next_12_months.scala.html
  app/views/msb/uses_foreign_currencies.scala.html
  app/views/msb/which_currencies.scala.html
  release_notes/AMLS-4923.txt
  test/views/msb/business_use_an_ipspSpec.scala
  test/views/msb/ce_transaction_in_next_12_monthsSpec.scala
  test/views/msb/fx_transaction_in_next_12_monthsSpec.scala
  test/views/msb/transactions_in_next_12_monthsSpec.scala
Labels: passed QA

#1102 Amls 5121 - Changing TP cya button
  app/views/tradingpremises/summary_details.scala.html
  conf/messages
  release_notes/AMLS-5121.txt
Labels: passed QA

#1103 Amls 4920 - Add h1 to legend for Pre-app Variation (Business Matching-Update Service)
  app/views/businessmatching/business_type.scala.html
  app/views/businessmatching/company_registration_number.scala.html
  app/views/businessmatching/register_services.scala.html
  app/views/businessmatching/updateservice/add/add_more_activities.scala.html
  app/views/businessmatching/updateservice/add/business_applied_for_psr_number.scala.html
  app/views/businessmatching/updateservice/add/fit_and_proper.scala.html
  app/views/businessmatching/updateservice/add/msb_subservices.scala.html
  app/views/businessmatching/updateservice/add/select_activities.scala.html
  app/views/businessmatching/updateservice/add/trading_premises.scala.html
  app/views/businessmatching/updateservice/add/what_do_you_do_here.scala.html
  app/views/businessmatching/updateservice/add/which_fit_and_proper.scala.html
  app/views/businessmatching/updateservice/add/which_trading_premises.scala.html
  app/views/businessmatching/updateservice/change_services.scala.html
  app/views/businessmatching/updateservice/remove/remove_activities.scala.html
  app/views/include/forms2/fieldsetWithErrorGroup.scala.html
  app/views/include/responsible_people.scala.html
  release_notes/AMLS-4920.txt
Labels: passed QA

#1104 AMLS-5101 - update to HVD h1 titles
  conf/messages
  release_notes/AMLS-5101.txt
Labels: passed QA

#1096 AMLS-4924: Accessibility for Responsible People
  app/views/businessdetails/confirm_registered_office_or_main_place.scala.html
  app/views/date_of_change.scala.html
  app/views/include/roles_within_business.scala.html
  app/views/responsiblepeople/approval_check.scala.html
  app/views/responsiblepeople/confirm_address.scala.html
  app/views/responsiblepeople/country_of_birth.scala.html
  app/views/responsiblepeople/date_of_birth.scala.html
  app/views/responsiblepeople/experience_training.scala.html
  app/views/responsiblepeople/fit_and_proper.scala.html
  app/views/responsiblepeople/known_by.scala.html
  app/views/responsiblepeople/legal_name.scala.html
  app/views/responsiblepeople/legal_name_change_date.scala.html
  app/views/responsiblepeople/moved_address.scala.html
  app/views/responsiblepeople/nationality.scala.html
  app/views/responsiblepeople/new_home_date_of_change.scala.html
  app/views/responsiblepeople/person_name.scala.html
  app/views/responsiblepeople/person_non_uk_passport.scala.html
  app/views/responsiblepeople/person_residence_type.scala.html
  app/views/responsiblepeople/person_uk_passport.scala.html
  app/views/responsiblepeople/position_within_business.scala.html
  app/views/responsiblepeople/position_within_business_start_date.scala.html
  app/views/responsiblepeople/registered_for_self_assessment.scala.html
  app/views/responsiblepeople/remove_responsible_person.scala.html
  app/views/responsiblepeople/sole_proprietor.scala.html
  app/views/responsiblepeople/time_at_additional_address.scala.html
  app/views/responsiblepeople/time_at_additional_extra_address.scala.html
  app/views/responsiblepeople/time_at_address.scala.html
  app/views/responsiblepeople/training.scala.html
  app/views/responsiblepeople/vat_registered.scala.html
  conf/messages
  release_notes/AMLS-4924.txt
  test/views/include/roles_within_businessSpec.scala
  test/views/responsiblepeople/remove_responsible_personSpec.scala
Labels: passed QA
