Repository hmrc/amls-frontend, pull requests merged in 2019-04, with the labels that each got.

#992 Amls 4238 - Rework question in EAB flow
  app/models/estateagentbusiness/RedressScheme.scala
  app/views/estateagentbusiness/redress_scheme.scala.html
  conf/messages
  release_notes/AMLS-4238.txt
  test/models/estateagentbusiness/RedressSchemeSpec.scala
  test/views/estateagentbusiness/redress_schemeSpec.scala
Labels: passed QA

#900 Amls 4626
  app/connectors/cache/DataCacheConnector.scala
  app/connectors/cache/MongoCacheConnector.scala
  app/controllers/businessmatching/updateservice/ChangeSubSectorHelper.scala
  app/controllers/businessmatching/updateservice/RemoveBusinessTypeHelper.scala
  app/services/LandingService.scala
  app/services/businessmatching/BusinessMatchingService.scala
  app/services/cache/MongoCacheClient.scala
  release_notes/AMLS-4626.txt
  test/controllers/businessmatching/updateservice/ChangeSubSectorHelperSpec.scala
  test/controllers/businessmatching/updateservice/RemoveBusinessTypeHelperSpec.scala
  test/services/LandingServiceSpec.scala
  test/services/businessmatching/BusinessMatchingServiceSpec.scala
  test/utils/CacheMocks.scala
Labels: pending QA

#1000 Release notes 4.311
  release_notes/AMLS-4123.txt
  release_notes/AMLS-4238.txt
  release_notes/AMLS-4515.txt
  release_notes/AMLS-4756.txt
  release_notes/AMLS-4772.txt
  release_notes/AMLS-4799.txt
  release_notes/AMLS-4800.txt
  release_notes/AMLS-4815.txt
  release_notes/AMLS-4818.txt
  release_notes/AMLS-4822.txt
  release_notes/AMLS-4835.txt
  release_notes/releases/v4.311.0/v4.311.0-05-04-2019.txt
Labels: Do-Not-Merge

#997 AMLS-4769 | New Payment Endpoint
  app/config/ApplicationConfig.scala
  app/connectors/PayApiConnector.scala
  app/controllers/ConfirmationController.scala
  app/controllers/payments/WaysToPayController.scala
  app/models/payments/CreatePaymentResponse.scala
  app/services/PaymentsService.scala
  release_notes/AMLS-4769.txt
  test/connectors/PayApiConnectorSpec.scala
  test/controllers/ConfirmationControllerSpec.scala
  test/controllers/payments/WaysToPayControllerSpec.scala
  test/generators/PaymentGenerator.scala
  test/models/payments/CreatePaymentResponseSpec.scala
  test/services/PaymentsServiceSpec.scala
Labels: pending QA

#996 Amls 4763
  app/views/asp/services_of_business.scala.html
  app/views/asp/summary.scala.html
  app/views/asp/what_you_need.scala.html
  app/views/supervision/summary.scala.html
  app/views/supervision/what_you_need.scala.html
  conf/asp.routes
  conf/messages
  conf/supervision.routes
  release_notes/AMLS-4763.txt
Labels: passed QA

#987 AMLS-4768 | Updated TCSP Content issues
  app/controllers/tcsp/SummaryController.scala
  app/models/tcsp/ProvidedServices.scala
  app/views/tcsp/another_tcsp_supervision.scala.html
  app/views/tcsp/provided_services.scala.html
  app/views/tcsp/service_provider_types.scala.html
  app/views/tcsp/summary.scala.html
  app/views/tcsp/what_you_need.scala.html
  conf/messages
  conf/tcsp.routes
  release_notes/AMLS-4768.txt
  test/controllers/tcsp/SummaryControllerSpec.scala
  test/models/tcsp/TcspServiceSpec.scala
  test/views/tcsp/summarySpec.scala
  test/views/tcsp/what_you_needSpec.scala
Labels: passed QA

#1005 AMLS-4763 | Few fixes after merge conflicts
  app/views/supervision/summary.scala.html
  app/views/supervision/which_professional_body.scala.html
  conf/asp.routes
  conf/messages
Labels: pending QA, pending review

#1003 Amls 4880 - fix to supervision/msb sections after page split
  app/controllers/msb/MoneySourcesController.scala
  app/controllers/supervision/AnotherBodyController.scala
  app/controllers/supervision/SupervisionEndReasonsController.scala
  app/utils/ControllerHelper.scala
  release_notes/AMLS-4880.txt
  test/controllers/msb/MoneySourcesControllerSpec.scala
  test/controllers/supervision/AnotherBodyControllerSpec.scala
  test/utils/ControllerHelperSpec.scala
Labels: pending QA

#1013 Fix release notes - remove url
  generate-my-release-note.sh
  release_notes/AMLS-4122.txt
  release_notes/AMLS-4198.txt
  release_notes/AMLS-4626.txt
  release_notes/AMLS-4671.txt
  release_notes/AMLS-4763.txt
  release_notes/AMLS-4768.txt
  release_notes/AMLS-4769.txt
  release_notes/AMLS-4823.txt
  release_notes/AMLS-4880.txt
  release_notes/AMLS-4891.txt
  release_notes/releases/v4.246.0/v4.246.0-21-02-2019.txt
  release_notes/releases/v4.257.0/v4.257.0-28-02-2019.txt
  release_notes/releases/v4.264.0/v4.264.0-05-03-2019.txt
  release_notes/releases/v4.276.0/v4.276.0-12-03-2019.txt
  release_notes/releases/v4.296.0/v4.296.0-20-03-2019.txt
  release_notes/releases/v4.311.0/v4.311.0-05-04-2019.txt
  release_notes/releases/v4.314.1/v4.314.1-08-04-2019.txt
Labels: pending review

#1006 AMLS-4858 | Content issue fix, summary page EAB
  app/views/estateagentbusiness/summary.scala.html
  release_notes/AMLS-4858.txt
  test/views/estateagentbusiness/summarySpec.scala
Labels: pending QA

#1010 AMLS-4821 | Fix - Country lookup field
  app/views/include/forms2/country_autocomplete.scala.html
  release_notes/AMLS-4821.txt
  test/views/include/country_autocompleteSpec.scala
Labels: pending QA

#1009 Amls 4837 - HVD/ASP renewal flow change
  app/controllers/renewal/AMLSTurnoverController.scala
  app/controllers/renewal/CustomersOutsideUKController.scala
  app/controllers/renewal/FXTransactionsInLast12MonthsController.scala
  app/controllers/renewal/MoneySourcesController.scala
  app/controllers/renewal/SendMoneyToOtherCountryController.scala
  app/controllers/renewal/TotalThroughputController.scala
  app/controllers/renewal/UsesForeignCurrenciesController.scala
  app/views/renewal/summary.scala.html
  release_notes/AMLS-4837.txt
  test/controllers/renewal/AMLSTurnoverControllerSpec.scala
  test/controllers/renewal/CustomersOutsideUKControllerSpec.scala
  test/controllers/renewal/FXTransactionsInLast12MonthsControllerSpec.scala
  test/controllers/renewal/MoneySourcesControllerSpec.scala
  test/controllers/renewal/SendMoneyToOtherCountryControllerSpec.scala
  test/controllers/renewal/TotalThroughputControllerSpec.scala
Labels: passed QA

#1007 Amls 4765 | msb content and contractions
  app/views/msb/branches_or_agents.scala.html
  app/views/msb/most_transactions.scala.html
  app/views/msb/send_largest_amounts_of_money.scala.html
  app/views/msb/what_you_need.scala.html
  app/views/msb/which_currencies.scala.html
  conf/messages
  conf/msb.routes
  release_notes/AMLS-4765.txt
Labels: passed QA

#1008 AMLS-4766 | Update to content for agent trading premises
  app/views/tradingpremises/agent_company_details.scala.html
  app/views/tradingpremises/agent_partnership.scala.html
  app/views/tradingpremises/business_structure.scala.html
  app/views/tradingpremises/msb_services.scala.html
  app/views/tradingpremises/summary_details.scala.html
  app/views/tradingpremises/what_you_need.scala.html
  conf/messages
  conf/tradingPremises.routes
  release_notes/AMLS-4766.txt
  test/views/tradingpremises/summary_detailsSpec.scala
  test/views/tradingpremises/what_you_needSpec.scala
Labels: passed QA

#1015 Amls 4717
  app/controllers/renewal/AMLSTurnoverController.scala
  app/controllers/renewal/InvolvedInOtherController.scala
  app/controllers/renewal/SummaryController.scala
  app/models/businessmatching/BusinessMatching.scala
  app/views/renewal/amls_turnover.scala.html
  app/views/renewal/involved_in_other.scala.html
  app/views/renewal/most_transactions.scala.html
  app/views/renewal/percentage.scala.html
  app/views/renewal/receiving.scala.html
  app/views/renewal/send_largest_amounts_of_money.scala.html
  app/views/renewal/summary.scala.html
  app/views/renewal/total_throughput.scala.html
  app/views/renewal/what_you_need.scala.html
  app/views/renewal/which_currencies.scala.html
  conf/messages
  conf/renewal.routes
  release_notes/AMLS-4717.txt
  test/controllers/deregister/DeRegisterApplicationControllerSpec.scala
  test/controllers/renewal/InvolvedInOtherControllerSpec.scala
  test/models/businessmatching/BusinessMatchingSpec.scala
  test/views/renewal/amls_turnoverSpec.scala
  test/views/renewal/involved_in_otherSpec.scala
  test/views/renewal/summarySpec.scala
  test/views/tradingpremises/summary_detailsSpec.scala
Labels: passed QA

#1018 AMLS-4872 AMLS-4898
  app/views/include/forms2/fieldset.scala.html
  app/views/include/forms2/legend.scala.html
  app/views/include/heading.scala.html
  app/views/supervision/supervision_end_reasons.scala.html
  conf/application.conf
  release_notes/AMLS-4869.txt
  release_notes/AMLS-4898.txt
Labels: build passing, pending QA

#1019 AMLS-4717 | Fix to failing unit test.
  test/controllers/renewal/PercentageOfCashPaymentOver15000ControllerSpec.scala
Labels: pending review

#1020 Generate release notes
  release_notes/AMLS-4170.txt
  release_notes/AMLS-4717.txt
  release_notes/AMLS-4765.txt
  release_notes/AMLS-4766.txt
  release_notes/AMLS-4837.txt
  release_notes/AMLS-4869.txt
  release_notes/AMLS-4898.txt
  release_notes/AMLS-4899.txt
  release_notes/releases/v4.346.0/v4.346.0-24-04-2019.txt
Labels: pending review

#1021 Amls 4771
  app/controllers/businessmatching/RegisterServicesController.scala
  release_notes/AMLS-4771.txt
  test/controllers/businessmatching/RegisterServicesControllerSpec.scala
Labels: passed QA
