Repository hmrc/amls-frontend, pull requests merged in 2020-03, with the labels that each got.

#1364 Amls 5664 - New AMP renewal page
  app/controllers/renewal/AMLSTurnoverController.scala
  app/controllers/renewal/AMPTurnoverController.scala
  app/models/amp/Amp.scala
  app/models/renewal/AMPTurnover.scala
  app/models/renewal/Conversions.scala
  app/models/renewal/Renewal.scala
  app/services/LandingService.scala
  app/services/RenewalService.scala
  app/views/renewal/amp_turnover.scala.html
  app/views/renewal/summary.scala.html
  conf/messages
  conf/renewal.routes
  release_notes/AMLS-5665.txt
  test/controllers/RegistrationProgressControllerSpec.scala
  test/controllers/StatusControllerSpec.scala
  test/controllers/declaration/DeclarationControllerSpec.scala
  test/controllers/payments/BankDetailsControllerSpec.scala
  test/controllers/payments/TypeOfBankControllerSpec.scala
  test/controllers/payments/WaysToPayControllerSpec.scala
  test/controllers/renewal/AMPTurnoverControllerSpec.scala
  test/controllers/renewal/SummaryControllerSpec.scala
  test/models/amp/AmpSpec.scala
  test/models/renewal/AMPTurnoverSpec.scala
  test/models/renewal/RenewalSpec.scala
  test/services/LandingServiceSpec.scala
  test/services/RenewalServiceSpec.scala
  test/services/SubmissionServiceSpec.scala
  test/utils/DeclarationHelperSpec.scala
  test/views/renewal/amp_turnoverSpec.scala
  test/views/renewal/summarySpec.scala
Labels: passed QA

#1375 Amls 5747 - MSB country pages H1 & error changes
  conf/messages
  release_notes/AMLS-5747.txt
Labels: passed QA

#1379 Amls 5765 - Withdraw and Deregister reasons content update
  app/models/deregister/DeregistrationReason.scala
  app/models/withdrawal/WithdrawalReason.scala
  app/views/deregister/deregistration_reason.scala.html
  app/views/withdrawal/withdrawal_reason.scala.html
  conf/app.routes
  conf/messages
  release_notes/AMLS-5765.txt
  test/models/deregister/DeregistrationReasonSpec.scala
  test/models/withdrawal/WithdrawalReasonSpec.scala
Labels: passed QA

#1383 AMLS-5775 | Added isComplete check in summary controller, to prevent …
  app/controllers/tcsp/SummaryController.scala
  app/controllers/tcsp/TcspTypesController.scala
  release_notes/AMLS-5775.txt
  test/controllers/tcsp/SummaryControllerSpec.scala
  test/controllers/tcsp/TcspTypesControllerSpec.scala
Labels: pending QA

#1389 AMLS-5804-fix | Updated ID field for PSR number
  app/views/businessmatching/summary.scala.html
Labels: pending review

#1378 Amls 5826 | Application ready to submit button on status page goes to wrong place fix
  app/controllers/StatusController.scala
  release_notes/AMLS-5826.txt
Labels: pending QA

#1374 Amls 5795 - Fix to missing status information when date not available.
  app/views/status/components/registration_status.scala.html
  conf/messages
  release_notes/AMLS-5795.txt
  test/views/status/your_registrationSpec.scala
Labels: pending QA

#1373 Amls 5796 - Cache validation and refresh from API5 if no cache when hitting status controller
  app/controllers/StatusController.scala
  app/services/RenewalService.scala
  release_notes/AMLS-5796.txt
  test/controllers/StatusControllerSpec.scala
Labels: pending QA

#1384 Amls 5766 - Withdraw and Deregister content changes
  app/views/deregister/deregister_application.scala.html
  app/views/withdrawal/withdraw_application.scala.html
  conf/app.routes
  conf/messages
  public/amls.css
  release_notes/AMLS-5766.txt
  test/controllers/deregister/DeRegisterApplicationControllerSpec.scala
  test/controllers/withdrawal/WithdrawApplicationControllerSpec.scala
  test/views/deregister/deregister_applicationSpec.scala
  test/views/withdrawal/withdraw_applicationSpec.scala
Labels: passed QA

#1392 Generated release notes for release v4.804.0
  release_notes/AMLS-5766.txt
  release_notes/AMLS-5774.txt
  release_notes/AMLS-5777.txt
  release_notes/AMLS-5795.txt
  release_notes/AMLS-5796.txt
  release_notes/AMLS-5805.txt
  release_notes/AMLS-5806.txt
  release_notes/AMLS-5812.txt
  release_notes/AMLS-5825.txt
  release_notes/AMLS-5826.txt
  release_notes/releases/v4.804.0/v4.804.0-23-03-2020.txt
Labels: pending review

#1394 Amls 5870 - Covid 19 banner
  app/config/ApplicationConfig.scala
  app/views/include/main2.scala.html
  conf/application.conf
  public/amls.css
  release_notes/AMLS-5870.txt
Labels: pending QA

#1388 Amls 5779 - Letting Agent DES Integration
  app/config/ApplicationConfig.scala
  app/controllers/LandingController.scala
  app/controllers/businessmatching/updateservice/RemoveBusinessTypeHelper.scala
  app/models/eab/Eab.scala
  app/models/estateagentbusiness/ClientMoneyProtectionScheme.scala
  app/models/estateagentbusiness/EstateAgentBusiness.scala
  app/models/estateagentbusiness/PenalisedUnderEstateAgentsAct.scala
  app/models/estateagentbusiness/ProfessionalBody.scala
  app/models/estateagentbusiness/RedressScheme.scala
  app/models/estateagentbusiness/Service.scala
  app/services/SectionsProvider.scala
  app/services/SubmissionService.scala
  app/services/businessmatching/BusinessMatchingService.scala
  app/views/login_event.scala.html
  conf/application.conf
  release_notes/AMLS-5779.txt
  test/controllers/estateagentbusiness/BusinessServicesControllerSpec.scala
  test/models/eab/EabSpec.scala
  test/models/estateagentbusiness/ClientMoneyProtectionSchemeSpec.scala
  test/services/SubmissionServiceSpec.scala
  test/services/UpdateMongoCacheServiceSpec.scala
Labels: passed QA

#1397 Generated release notes for release 4.808.0
  release_notes/AMLS-5832.txt
  release_notes/releases/v4.808.0/v4.808.0-25-03-2020.txt
Labels: pending review
