Repository hmrc/amls-frontend, pull requests merged in 2020-05, with the labels that each got.

#1439 Amls 5919 - Renewals HVD Percentage Turnover always sent to DES as 0%-20%
  app/models/renewal/PercentageOfCashPaymentOver15000.scala
  release_notes/AMLS-5919.txt
  test/models/renewal/ConversionsSpec.scala
Labels: passed QA

#1441 Amls 5877 - WYN content changes
  app/controllers/businessactivities/WhatYouNeedController.scala
  app/controllers/renewal/WhatYouNeedController.scala
  app/controllers/responsiblepeople/WhatYouNeedController.scala
  app/controllers/tradingpremises/WhatYouNeedController.scala
  app/models/renewal/MoneySources.scala
  app/views/bankdetails/what_you_need.scala.html
  app/views/businessactivities/what_you_need.scala.html
  app/views/businessdetails/what_you_need.scala.html
  app/views/declaration/register_responsible_person.scala.html
  app/views/hvd/what_you_need.scala.html
  app/views/msb/what_you_need.scala.html
  app/views/renewal/what_you_need.scala.html
  app/views/responsiblepeople/what_you_need.scala.html
  app/views/supervision/what_you_need.scala.html
  app/views/tcsp/what_you_need.scala.html
  app/views/tradingpremises/what_you_need.scala.html
  conf/messages
  release_notes/AMLS-5877.txt
  test/controllers/businessactivities/WhatYouNeedControllerSpec.scala
  test/controllers/renewal/WhatYouNeedControllerSpec.scala
  test/controllers/responsiblepeople/WhatYouNeedControllerSpec.scala
  test/controllers/tradingpremises/WhatYouNeedControllerSpec.scala
  test/views/asp/what_you_needSpec.scala
  test/views/bankdetails/what_you_needSpec.scala
  test/views/businessactivities/what_you_needSpec.scala
  test/views/businessdetails/what_you_needSpec.scala
  test/views/declaration/register_responsible_personSpec.scala
  test/views/hvd/what_you_needSpec.scala
  test/views/msb/what_you_needSpec.scala
  test/views/renewal/what_you_needSpec.scala
  test/views/responsiblepeople/what_you_needSpec.scala
  test/views/responsiblepeople/who_must_registerSpec.scala
  test/views/supervision/what_you_needSpec.scala
  test/views/tcsp/what_you_needSpec.scala
  test/views/tradingpremises/what_you_needSpec.scala
Labels: Do-Not-Merge

#1462 Generate release notes for v4.847.0
  release_notes/AMLS-5808.txt
  release_notes/AMLS-5809.txt
  release_notes/AMLS-5810.txt
  release_notes/AMLS-5811.txt
  release_notes/AMLS-5815.txt
  release_notes/AMLS-5820.txt
  release_notes/AMLS-5877.txt
  release_notes/AMLS-5919.txt
  release_notes/releases/v4.847.0/v4.847.0-13-05-2020.txt
Labels: pending review

#1467 Fix redress redirect to eab from interrupt page
  app/config/ApplicationConfig.scala
  app/controllers/LoginEventController.scala
  app/views/login_event.scala.html
  test/views/login_eventSpec.scala
Labels: pending review

#1466 Amls 5925 - address for letters content update
  app/views/businessdetails/summary.scala.html
  conf/messages
  release_notes/AMLS-5925.txt
Labels: pending QA

#1464 Amls 5934 | DAC markup issue fix.
  app/views/include/forms2/fieldsetWithErrorGroup.scala.html
  release_notes/AMLS-5934.txt
Labels: passed QA

#1463 Amls 5759 | Update H1 on Confirm the postcode page in pre-application and improve routing
  app/controllers/LandingController.scala
  app/controllers/businessdetails/ConfirmRegisteredOfficeController.scala
  app/controllers/businessmatching/ConfirmPostCodeController.scala
  app/models/Country.scala
  app/models/FormTypes.scala
  app/models/businesscustomer/ReviewDetails.scala
  app/models/businessmatching/ConfirmPostcode.scala
  app/views/businessmatching/confirm_postcode.scala.html
  conf/messages
  release_notes/AMLS-5759.txt
  test/controllers/LandingControllerWithoutAmendmentsSpec.scala
  test/controllers/businessdetails/ConfirmRegisteredOfficeControllerSpec.scala
  test/controllers/businessmatching/ConfirmPostCodeControllerSpec.scala
  test/models/businessmatching/ConfirmPostcodeSpec.scala
  test/models/businessmatching/ReviewDetailsSpec.scala
Labels: pending QA, pending review
