Repository hmrc/amls-frontend, pull requests merged in 2020-06, with the labels that each got.

#1475 Amls 5917 | Remove TODO from code
  app/config/ApplicationConfig.scala
  app/services/UpdateMongoCacheService.scala
  public/amls.css
  public/characterCount.js
  release_notes/AMLS-5917.txt
  upversion-templates.sh
Labels: reviewed

#1477 Amls 5842 - Accessibility statement + footer link + toggle
  app/config/ApplicationConfig.scala
  app/controllers/accessibility/AccessibilityStatementController.scala
  app/views/accessibility/accessibility_statement.scala.html
  app/views/include/main.scala.html
  app/views/include/main2.scala.html
  conf/app.routes
  conf/application.conf
  conf/messages
  release_notes/AMLS-5842.txt
  test/controllers/accessibility/AccessibilityStatementControllerSpec.scala
  test/views/accessibility/accessibilityStatementSpec.scala
Labels: pending QA

#1483 AMLS-5842 | Added security target on link
  app/views/accessibility/accessibility_statement.scala.html
Labels: pending QA

#1482 Amls | Removed unused toggle
  conf/application.conf
  test/models/governmentgateway/EnrolmentRequestSpec.scala
Labels: pending QA, pending review

#1488 AMLS-BetaHeadingRemoval | Removal of beta heading
  README.md
  app/views/include/main.scala.html
  app/views/include/main2.scala.html
Labels: pending review
